trellis-ldp/trellis

buildtools/src/install/install-jdk-10.sh
JDK 10 ea binaries apparently now have a different location.
=> Fix JDK 10 install script

trellis-api/src/main/java/org/trellisldp/api/ResourceService.java, trellis-api/src/test/java/org/trellisldp/api/ConstraintServiceTest.java, trellis-api/src/test/java/org/trellisldp/api/ResourceServiceTest.java, trellis-event-serialization/src/test/java/org/trellisldp/event/EventSerializerTest.java, trellis-http/src/main/java/org/trellisldp/http/LdpResource.java, trellis-http/src/main/java/org/trellisldp/http/impl/BaseLdpHandler.java, trellis-http/src/main/java/org/trellisldp/http/impl/MementoResource.java, trellis-http/src/test/java/org/trellisldp/http/AbstractLdpResourceTest.java, trellis-http/src/test/java/org/trellisldp/http/CORSResourceTest.java, trellis-http/src/test/java/org/trellisldp/http/LdpForbiddenResourceTest.java, trellis-http/src/test/java/org/trellisldp/http/LdpUnauthorizedResourceTest.java, trellis-io-jena/src/test/java/org/trellisldp/io/IOServiceTest.java, trellis-vocabulary/src/test/java/org/trellisldp/vocabulary/ACLTest.java, trellis-vocabulary/src/test/java/org/trellisldp/vocabulary/ASTest.java, trellis-vocabulary/src/test/java/org/trellisldp/vocabulary/AbstractVocabularyTest.java, trellis-vocabulary/src/test/java/org/trellisldp/vocabulary/DCTest.java, trellis-vocabulary/src/test/java/org/trellisldp/vocabulary/FOAFTest.java, trellis-vocabulary/src/test/java/org/trellisldp/vocabulary/JSONLDTest.java, trellis-vocabulary/src/test/java/org/trellisldp/vocabulary/LDPTest.java, trellis-vocabulary/src/test/java/org/trellisldp/vocabulary/MementoTest.java, trellis-vocabulary/src/test/java/org/trellisldp/vocabulary/OATest.java, trellis-vocabulary/src/test/java/org/trellisldp/vocabulary/PROVTest.java, trellis-vocabulary/src/test/java/org/trellisldp/vocabulary/RDFSTest.java, trellis-vocabulary/src/test/java/org/trellisldp/vocabulary/RDFTest.java, trellis-vocabulary/src/test/java/org/trellisldp/vocabulary/SKOSTest.java, trellis-vocabulary/src/test/java/org/trellisldp/vocabulary/TimeTest.java, trellis-vocabulary/src/test/java/org/trellisldp/vocabulary/TrellisTest.java, trellis-vocabulary/src/test/java/org/trellisldp/vocabulary/VCARDTest.java, trellis-webac/src/main/java/org/trellisldp/webac/WebACService.java, trellis-webac/src/test/java/org/trellisldp/webac/WebACServiceTest.java
Two commits here: the first will be uncontroversial, I think-- it just adds in some type params to avoid compiler warnings. Maybe there's a reason not to, and if so, let's just skip it.
The other widens the return type of `ResourceService::get` (in both forms) in order to deal with Java's craptacular generics and their lack of proper co/contravariance control. Because `ResourceService::get` returns `Optional<Resource>`, I can't impl it with `Optional<MyTypeThatImplsResource>` because Java doesn't understand that `Optional<MyTypeThatImplsResource> "extends" Optional<Resource>`. So now I can, at the cost of making some test mocking code look pretty gross... this lets impls of `ResourceService` use `get` in their own code and get the actual type of `Resource` at stake. _This_ is useful …
=> Type stuff

.gitignore, trellis-api/src/main/java/org/trellisldp/api/AppendService.java, trellis-api/src/main/java/org/trellisldp/api/AuditService.java, trellis-api/src/main/java/org/trellisldp/api/RDFUtils.java, trellis-api/src/main/java/org/trellisldp/api/ReplaceService.java, trellis-api/src/main/java/org/trellisldp/api/ResourceService.java, trellis-api/src/main/java/org/trellisldp/api/RetrievalService.java, trellis-audit/build.gradle, trellis-audit/src/main/java/org/trellisldp/audit/DefaultAuditService.java, trellis-karaf/src/main/resources/features.xml, trellis-test/src/test/java/org/trellisldp/test/OSGiTest.java, trellis-triplestore/build.gradle, trellis-triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, trellis-triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceTest.java
Introducing new types for persistence, but not yet weaving them all the way through the module stack.
=> Rearrange the furniture

trellis-constraint-rules/src/main/java/org/trellisldp/constraint/LdpConstraints.java, trellis-constraint-rules/src/test/java/org/trellisldp/constraint/LdpConstraintsTest.java
=> Relax constraints on rdf:type

build.gradle, trellis-app/src/main/resources/banner.txt
a trivial change that has one function, to notify the console with a build version.  The style of the banner is bolder and reflects the solidity of the Trellis design.  Also, gradle will not process a resource with the special characters contained in the original version.
=> adds version to banner and changes style

trellis-api/src/main/java/org/trellisldp/api/ImmutableDataService.java, trellis-api/src/main/java/org/trellisldp/api/JoiningResourceService.java, trellis-api/src/main/java/org/trellisldp/api/MutableDataService.java, trellis-api/src/main/java/org/trellisldp/api/RDFUtils.java, trellis-api/src/main/java/org/trellisldp/api/ResourceService.java, trellis-api/src/main/java/org/trellisldp/api/Session.java, trellis-api/src/test/java/org/trellisldp/api/JoiningResourceServiceTest.java, trellis-app/build.gradle, trellis-app/src/test/java/org/trellisldp/app/TrellisEventTest.java, trellis-http/src/main/java/org/trellisldp/http/MultipartUploader.java, trellis-http/src/main/java/org/trellisldp/http/impl/DeleteHandler.java, trellis-http/src/main/java/org/trellisldp/http/impl/HttpSession.java, trellis-http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, trellis-http/src/main/java/org/trellisldp/http/impl/PostHandler.java, trellis-http/src/main/java/org/trellisldp/http/impl/PutHandler.java, trellis-http/src/test/java/org/trellisldp/http/AbstractLdpResourceTest.java, trellis-http/src/test/java/org/trellisldp/http/CORSResourceTest.java, trellis-http/src/test/java/org/trellisldp/http/LdpForbiddenResourceTest.java, trellis-http/src/test/java/org/trellisldp/http/LdpUnauthorizedResourceTest.java, trellis-http/src/test/java/org/trellisldp/http/impl/DeleteHandlerTest.java, trellis-http/src/test/java/org/trellisldp/http/impl/HttpSessionTest.java, trellis-http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java, trellis-http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, trellis-http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java, trellis-triplestore/src/main/java/org/trellisldp/triplestore/SimpleEvent.java, trellis-triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, trellis-triplestore/src/test/java/org/trellisldp/triplestore/SimpleSession.java, trellis-triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreEventTest.java, trellis-triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java
Resolves #56 and #57
This updates the Trellis API ResourceService methods
by adding session-related data in a distinct type.
This fixes errors in the event stream where event type and agent
data were missing from messages.
=> Add session information to API methods

buildtools/src/install/install-jdk-10.sh
JDK 10 is now GA and the download URL has changed.
Eventually travis will make this even easier....
=> Update JDK 10 download URL

trellis-app/src/main/java/org/trellisldp/app/TrellisApplication.java
This commit introduces `protected` methods for most of the parts of a running Trellis instance, in order to make subclassing `TrellisApplication` less filled with cut-and-paste.
=> Factoring apart component builds for easier overriding

trellis-app/src/main/java/org/trellisldp/app/TrellisApplication.java
The whole point of my last PR was to make it easier to subclass `TrellisApplication`, but I forgot to make config available to subclasses!
=> Making environment and config protected for use by subclasses

trellis-api/src/main/java/org/trellisldp/api/ResourceService.java
Fix for https://github.com/trellis-ldp/trellis/issues/77
=> Minor Javadoc correction

trellis-test/src/main/java/org/trellisldp/test/BaseCommonTests.java
Fixes https://github.com/trellis-ldp/trellis/issues/80
=> Make getResourcePath overridable for build systems other than Gradle

trellis-app/src/main/java/org/trellisldp/app/config/TrellisConfiguration.java, trellis-app/src/test/java/org/trellisldp/app/config/TrellisConfigurationTest.java, trellis-app/src/test/resources/config1.yml
Adds configuration for use with [Trellis-Cassandra](https://github.com/ajs6f/trellis-cassandra).
=> Offering extended configuration

trellis-api/src/test/java/org/trellisldp/api/NoopNamespaceServiceTest.java
The tests for `NoopNamespaceService` are not currently enabled. This change enables them.
=> enable tests on NoopNamespaceService

build.gradle, trellis-api/src/main/java/org/trellisldp/api/ResourceService.java, trellis-api/src/test/java/org/trellisldp/api/JoiningResourceServiceTest.java, trellis-http/build.gradle, trellis-http/src/main/java/org/trellisldp/http/impl/BaseLdpHandler.java, trellis-http/src/main/java/org/trellisldp/http/impl/DeleteHandler.java, trellis-http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, trellis-http/src/main/java/org/trellisldp/http/impl/PostHandler.java, trellis-http/src/main/java/org/trellisldp/http/impl/PutHandler.java, trellis-http/src/test/java/org/trellisldp/http/AbstractLdpResourceTest.java, trellis-http/src/test/java/org/trellisldp/http/impl/DeleteHandlerTest.java, trellis-http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java, trellis-http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, trellis-http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java, trellis-karaf/src/main/resources/features.xml, trellis-triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, trellis-vocabulary/src/main/java/org/trellisldp/vocabulary/Trellis.java
Resolves #92 
Once we have agreement on this approach, I can apply it to #88, allowing the test suite to adjust to varying levels of LDP container support.
I decided _not_ to include a default implementation in the interface -- if we want implementations to be clear about what is supported, then I thought it makes more sense to simply require an implementing class to _implement_ the method.
I am also making use of a new named individual in the Trellis ontology `trellis:InvalidInteractionModel`, which is used with the `ldp:constrainedBy` link header in the case of an error condition.
=> Add ResourceService::supportedInteractionModels method

components/test/src/main/java/org/trellisldp/test/ResourceServiceTests.java
This fixes the common tests in `org.trellisldp.test.ResourceService`. It doesn't touch the `TriplestoreResourceService` tests.
=> Fix ResourceService tests

components/file/build.gradle, components/file/src/main/java/org/trellisldp/file/FileBinaryService.java, components/file/src/test/java/org/trellisldp/file/FileBinaryServiceTest.java, components/file/src/test/java/org/trellisldp/file/FileResourceTest.java, components/file/src/test/resources/binary.nq, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceTest.java, core/http/src/test/java/org/trellisldp/http/AbstractLdpResourceTest.java, core/http/src/test/java/org/trellisldp/http/CORSResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/GetHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/OptionsHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java
Resolves #128
Internal file URIs for binary locations have been using
a `file:foo/bar` format, but this is invalid according to RFC 8089,
the "file" URI scheme: https://tools.ietf.org/html/rfc8089
With this change, those internal IRIs are represented as
`file:///foo/bar`.
=> Follow File URI specification

components/test/src/main/java/org/trellisldp/test/ResourceServiceTests.java, components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java, core/api/src/main/java/org/trellisldp/api/JoiningResourceService.java, core/api/src/main/java/org/trellisldp/api/MutableDataService.java, core/api/src/test/java/org/trellisldp/api/JoiningResourceServiceTest.java, core/http/src/main/java/org/trellisldp/http/MultipartUploader.java, core/http/src/main/java/org/trellisldp/http/impl/DeleteHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractLdpResourceTest.java, core/http/src/test/java/org/trellisldp/http/CORSResourceTest.java, core/http/src/test/java/org/trellisldp/http/LdpForbiddenResourceTest.java, core/http/src/test/java/org/trellisldp/http/LdpUnauthorizedResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/DeleteHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java
Resolves #126 
The changes in the test code are pretty uninteresting. Of note are the changes in `core/api` and `core/http`.
=> Simplify Binary metadata handling in HTTP layer

build.gradle, components/file/build.gradle, components/io-jena/build.gradle, components/namespaces/build.gradle, notifications/jms/build.gradle, platform/karaf/build.gradle, platform/linux/build.gradle, platform/osgi/build.gradle, platform/webapp/build.gradle
Resolves #149 
With Gradle 4.8 (we currently use 4.7 for this project), the `maven` plugin becomes deprecated in favor of the `maven-publish` plugin. This PR converts to using the new plugin. The changes primarily relate to signing, POM generation along with a few other items. Because I'm so used to issuing `gradle install` and `gradle upload`, this also aliases the relevant tasks to those commands.
=> Convert from maven to maven-publish plugin

components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java, core/api/src/main/java/org/trellisldp/api/ResourceService.java, core/api/src/test/java/org/trellisldp/api/JoiningResourceServiceTest.java
Resolves #162 
This removes some code that is not used, and there are no plans to start using it.
=> Remove ResourceService::compact method

build.gradle, components/file/build.gradle, components/file/src/main/java/org/trellisldp/file/FileBinaryService.java, components/file/src/test/java/org/trellisldp/file/FileBinaryServiceTest.java, core/api/src/main/java/org/trellisldp/api/BinaryService.java, core/api/src/test/java/org/trellisldp/api/BinaryServiceTest.java, core/http/src/main/java/org/trellisldp/http/HttpBasedBinaryService.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractLdpResourceTest.java, core/http/src/test/java/org/trellisldp/http/HttpBasedBinaryServiceTest.java, platform/karaf/src/main/resources/features.xml
Resolves #169 
This changes the `BinaryService::getContent` method to support only a single range request (e.g. `Range: bytes=300-400` rather than multiple ranges (until there is a real use case for such a thing, I'd prefer to keep the interface as simple as possible).
The new interface is `BinaryService::getContent(IRI identifier, Integer from, Integer to)`
In addition, the default implementation of the `::getContent(IRI)` method has been removed, as it made a lot of assumptions about the implementation details of the 3-arity version of the method.
=> Simplify the BinaryService::getContent method

components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, core/api/src/main/java/org/trellisldp/api/ImmutableDataService.java, core/api/src/main/java/org/trellisldp/api/JoiningResourceService.java, core/api/src/main/java/org/trellisldp/api/MutableDataService.java, core/api/src/test/java/org/trellisldp/api/JoiningResourceServiceTest.java, core/http/src/test/java/org/trellisldp/http/AbstractLdpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/DeleteHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java
This is an incremental PR that includes the simplest parts of a refactor related to #148. In particular, this changes existing `Future` types to `CompletableFuture` types in the `ResourceService` mutating methods. It does not change any of the fetching methods. Changing the `::get` method will result in more significant changes, which will happen separately.
=> Initial refactor with CompletableFuture interfaces

components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java, core/api/src/main/java/org/trellisldp/api/ResourceService.java, core/api/src/test/java/org/trellisldp/api/JoiningResourceServiceTest.java, core/api/src/test/java/org/trellisldp/api/ResourceServiceTest.java
Resolves #179 
See related [discussion](https://github.com/trellis-ldp/trellis/pull/177#discussion_r205971740)
=> Remove ::scan and ::export from ResourceService

components/file/src/main/java/org/trellisldp/file/FileBinaryService.java, components/file/src/test/java/org/trellisldp/file/FileBinaryServiceTest.java, core/api/src/main/java/org/trellisldp/api/BinaryService.java, core/api/src/test/java/org/trellisldp/api/BinaryServiceTest.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractLdpResourceTest.java, core/http/src/test/java/org/trellisldp/http/BaseLdpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/HandlerBaseTest.java
Completes #148 
This updates the BinaryService interface to make use of asynchronous processing (via `CompletableFuture`). Changes in this interface result in changes to the `file` and `http` components.
=> Rework BinaryService to use CompletableFuture

components/test/src/main/java/org/trellisldp/test/MementoTimeGateTests.java, core/http/src/main/java/org/trellisldp/http/LdpResource.java, core/http/src/test/java/org/trellisldp/http/AbstractLdpResourceTest.java
Resolves #188
Datetime negotiation that would result in a non-existent
Memento should result in a `406 Not Acceptable` rather than
a `404 Not Found`.
=> Datetime negotiation of non-existent Mementos

components/test/src/main/java/org/trellisldp/test/ResourceServiceTests.java, components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java, core/api/src/main/java/org/trellisldp/api/BinaryService.java, core/api/src/main/java/org/trellisldp/api/ImmutableDataService.java, core/api/src/main/java/org/trellisldp/api/JoiningResourceService.java, core/api/src/main/java/org/trellisldp/api/MementoService.java, core/api/src/main/java/org/trellisldp/api/MutableDataService.java, core/api/src/test/java/org/trellisldp/api/JoiningResourceServiceTest.java, core/http/src/main/java/org/trellisldp/http/impl/BaseLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/DeleteHandler.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/BaseLdpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/DeleteHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/HandlerBaseTest.java, core/http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java
Resolves #183
The changes mutating async methods such that they return
`CompletableFuture<Void>` rather than `CompletableFuture<Boolean>`.
=> Make async return types consistent

components/test/src/main/java/org/trellisldp/test/AbstractApplicationAuthTests.java, components/test/src/main/java/org/trellisldp/test/AuthAnonymousTests.java, components/test/src/main/java/org/trellisldp/test/AuthUserTests.java, components/webac/src/main/java/org/trellisldp/webac/WebACService.java, components/webac/src/test/java/org/trellisldp/webac/WebACServiceTest.java
Resolves #199 
The change here is that a parent resource with an Authorization with `<> acl:default <>` will have its ACL statements inherited; if that `acl:default` statement is not present, then a further parent container will be checked. The root resource does not need the `acl:default` statement, as it is a global catch-all.
=> Adjust how the webac module interprets acl:default

components/io-jena/src/test/java/org/trellisldp/io/IOServiceTest.java, components/namespaces/build.gradle, components/namespaces/src/main/java/org/trellisldp/namespaces/NamespacesJsonContext.java, components/namespaces/src/test/java/org/trellisldp/namespaces/NamespacesJsonContextTest.java, components/rdfa/build.gradle, components/rdfa/src/main/java/org/trellisldp/rdfa/HtmlData.java, components/rdfa/src/test/java/org/trellisldp/rdfa/HtmlSerializerTest.java, core/api/src/main/java/org/trellisldp/api/NamespaceService.java, core/api/src/main/java/org/trellisldp/api/NoopNamespaceService.java, core/api/src/test/java/org/trellisldp/api/NoopNamespaceServiceTest.java
Resolves #221
This removes some NamespaceService methods that either aren't used or which could be easily refactored out of existence.
=> Simplify NamespaceService interface

components/app/src/main/java/org/trellisldp/app/AbstractTrellisApplication.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpFilter.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/test/java/org/trellisldp/http/LdpAdminResourceTest.java, core/http/src/test/java/org/trellisldp/http/LdpResourceNoAgentTest.java, core/http/src/test/java/org/trellisldp/http/LdpResourceTest.java, core/http/src/test/java/org/trellisldp/http/LdpUserResourceTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpFilterTest.java, platform/webapp/src/main/java/org/trellisldp/webapp/TrellisApplication.java
Resolves #203 
This just extracts the `ContainerRequestFilter` portions of the current `TrellisHttpResource` class into its own class.
=> Separate Trellis resource matcher and request filter

core/http/src/main/java/org/trellisldp/http/CacheControlFilter.java, core/http/src/main/java/org/trellisldp/http/CrossOriginResourceSharingFilter.java, core/http/src/main/java/org/trellisldp/http/WebSubHeaderFilter.java, core/http/src/test/java/org/trellisldp/http/BaseCORSTest.java, core/http/src/test/java/org/trellisldp/http/CORSDefaultConfigurationTest.java, core/http/src/test/java/org/trellisldp/http/CacheControlFilterTest.java, core/http/src/test/java/org/trellisldp/http/LdpAdminResourceTest.java, core/http/src/test/java/org/trellisldp/http/LdpResourceNoAgentTest.java, core/http/src/test/java/org/trellisldp/http/LdpResourceTest.java, core/http/src/test/java/org/trellisldp/http/LdpUserResourceTest.java, core/http/src/test/java/org/trellisldp/http/WebSubHeaderFilterTest.java
Resolves #223
This adds no-arg constructors to the existing CORS, WebSub and CacheControl filters.
=> Add injectable, no-arg constructors for HTTP filters

core/http/src/main/java/org/trellisldp/http/core/HttpConstants.java, core/http/src/main/java/org/trellisldp/http/impl/MementoResource.java, core/http/src/test/java/org/trellisldp/http/impl/MementoResourceTest.java
Resolves #239 
I'd like to wait on this until we hear back from the Memento folks, but this PR suppresses the `from` and `until` parameters of TimeMap Link headers by default. Using a configuration value, one can turn those back on.
=> Make optional memento link parameters configurable

components/io-jena/src/main/java/org/trellisldp/io/JenaIOService.java
This moves the injection point for the Jena-based IO Service to the no-arg constructor.
@ajs6f is this a good idea? Would this make things easier or harder for CDI? We can certainly leave this as it is, if that would be preferable; otherwise, I'd like to start to favor the no-arg constructors for dependency injection.
=> Adjust injection constructor on IO service

.travis.yml, platform/osgi/build.gradle
This changes the osgi build configuration so that tests are run only
if the itests profile is enabled.
Resolves #259
=> Add itests profile

components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java, core/api/src/main/java/org/trellisldp/api/ResourceService.java, core/api/src/test/java/org/trellisldp/api/JoiningResourceServiceTest.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java
Resolves #257 
This adjusts the core interfaces to introduce a `ResourceService::touch` method, and applies the changes to the HTTP layer.
The first commit adds the method and makes use of it in the HTTP layer.
The second commit adds an implementation in the triplestore persistence layer.
=> Add ResourceService::touch method

components/webac/src/main/java/org/trellisldp/webac/WebACService.java, components/webac/src/test/java/org/trellisldp/webac/WebACServiceTest.java, core/api/src/main/java/org/trellisldp/api/RDFUtils.java, core/api/src/main/java/org/trellisldp/api/ResourceService.java
Related to #264 
This sets the stage for reworking the ResourceService::getContainer method.
=> Move getContainer logic inside the WebAC service

build.gradle, components/file/build.gradle, components/file/src/main/java/org/trellisldp/file/FileBinaryService.java, components/file/src/main/java/org/trellisldp/file/FileMementoService.java, components/file/src/test/java/org/trellisldp/file/FileMementoServiceTest.java, core/api/build.gradle, core/api/src/main/java/org/trellisldp/api/MementoService.java, core/api/src/main/java/org/trellisldp/api/NoopMementoService.java, core/api/src/test/java/org/trellisldp/api/NoopMementoServiceTest.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/MementoResource.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, platform/karaf/src/main/resources/features.xml, platform/webapp/build.gradle
Resolves #263
This removes the dependency on `commons-lang3` and changes the `MementoService::list` method to `MementoService::mementos`, now returning a `CompletableFuture<SortedSet<Instant>>`
=> Rework MementoService interface

components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResource.java, components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceTest.java
Resolves #284
The "server managed" data structure is converted to a Map
in order to avoid any potential resource leakage. This also
removes output of any PreferServerManaged quads from the
::stream method.
=> Remove "server managed" triple output

core/http/src/main/java/org/trellisldp/http/impl/MementoResource.java
Related to #287 
IIRC, this weird subtraction/addition was in place to support millisecond precision Mementos in certain circumstances. I am not convinced that it is correct, and so this commit just truncates the memento to the closest second, which is the smallest resolution supported by RFC 1123 (upon which Memento is based).
If this fixes the issue referred to, then we should go further and make the `?version=...` URL parameters (for Mementos) have second precision, too. (They currently have millisecond precision)
=> Truncate Instants to second precision

components/test/src/main/java/org/trellisldp/test/CommonTests.java, components/test/src/main/java/org/trellisldp/test/LdpBinaryTests.java, components/test/src/main/java/org/trellisldp/test/MementoBinaryTests.java, components/test/src/main/java/org/trellisldp/test/MementoResourceTests.java, components/test/src/main/java/org/trellisldp/test/MementoTimeGateTests.java, platform/webapp/src/test/java/org/trellisldp/webapp/TrellisApplicationTest.java
Resolves #283 
This updates the test code to explicitly fetch LDP-NR descriptions when RDF is being requested.
=> Fetch LDP-NR descriptions for tests

components/file/src/main/java/org/trellisldp/file/FileBinaryService.java, components/file/src/test/java/org/trellisldp/file/FileBinaryServiceTest.java, core/api/src/main/java/org/trellisldp/api/BinaryService.java, core/api/src/test/java/org/trellisldp/api/BinaryServiceTest.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java, core/http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java
Resolves #305 
Note: this does not resolve the `File` buffering issue mentioned in #305; that will be addressed separately.
=> Simplify BinaryService::setContent method

core/api/src/main/java/org/trellisldp/api/BinaryService.java
I'd like to be able to return a `CompletableFuture<MyImplResource>` from `get` to reuse inside my impl.
=> Open BinaryService return type

components/file/src/main/java/org/trellisldp/file/FileBinaryService.java, components/file/src/test/java/org/trellisldp/file/FileBinaryServiceTest.java, core/api/build.gradle, core/api/src/main/java/org/trellisldp/api/BinaryService.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceForbiddenTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceUnauthorizedTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java, core/http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java
Resolves #316
This moves the processing of incoming binary streams to the
BinaryService by adding an additional BinaryService::setContent method.
This method accepts an additional argument: `algorithm`, and responds
with `CompletableFuture<String>` where that response string is the
value of the computed digest. If the value of that digest is null, one
should take that to mean that the supplied algorithm was not supported.
If the digest value does not match the expected value, it is the
reponsibility of the client code (e.g. in the HTTP layer) to call
BinaryService::purgeContent. A runtime exception, on the other hand,
would indicate a server error.
=> Move incoming binary digest handling to BinaryService

components/file/src/main/java/org/trellisldp/file/FileBinaryService.java, components/file/src/test/java/org/trellisldp/file/FileBinaryServiceTest.java, core/api/src/main/java/org/trellisldp/api/BinaryService.java, core/api/src/test/java/org/trellisldp/api/BinaryServiceTest.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java, core/http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java
Resolves #328
This passes HTTP headers into the BinaryService, which can
be used as a form of storage hint. They can also be entirely ignored.
=> Add hints to the BinaryService layer

components/file/src/main/java/org/trellisldp/file/FileBinaryService.java, components/file/src/test/java/org/trellisldp/file/FileBinaryServiceTest.java, core/api/src/main/java/org/trellisldp/api/BinaryMetadata.java, core/api/src/main/java/org/trellisldp/api/BinaryService.java, core/api/src/test/java/org/trellisldp/api/BinaryServiceTest.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java, core/http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java
WDYT @acoburn ? I think this is cleaner and makes for less use of `emotyMap()` all through the test code.
I'm also returning `MessageDigest` from checksum operations because there are a bunch of `public` methods on it (e.g. `digest(byte[] buf, int offset, int len)`) that are very legitimately useful.
=> Moving hints into BinaryMetadata

core/http/src/main/java/org/trellisldp/http/WebAcFilter.java, core/http/src/test/java/org/trellisldp/http/WebAcFilterTest.java
Resolves #350
Related to #349
This will allow extension modules to make use of the WebAC request
filter even if they define additional HTTP methods. This also makes
some of the internal methods more visible to support subclassing this filter.
=> Make HTTP method checking more flexible in WebACFilter

components/webac/src/main/java/org/trellisldp/webac/WebACService.java
Make `WebACService` a CDI `@Alternative` to avoid ambiguity with `NoopAccessControlService`
=> Make `WebACService` a CDI `@Alternative`

components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAVRequestFilter.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpFilter.java, core/http/src/main/java/org/trellisldp/http/core/Slug.java, core/http/src/main/java/org/trellisldp/http/core/TrellisRequest.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/core/SlugTest.java
Resolves #376 
Slug values should be URL-decoded, so this adds a new `http.core.Slug` class for handling this step. The rest of the changes are, effectively, adding test cases.
There are also some behavior changes, namely:
1. if the `Slug` headers contains any `/` characters, those will be replaced with an underscore rather than causing the entire request to fail (which is the current behavior)
2. `Slug` headers with whitespace characters will have that whitespace also replaced with underscores.
3. `Slug` headers with a fragment IRI (`#foo`) will have that fragment stripped off
4. `Slug` headers with query parameters (`?bar=baz`) will have that stripped off
=> Improve handling of client-provided Slug header

components/test/src/main/java/org/trellisldp/test/LdpRdfTests.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java, core/http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java
Resolves #386
This also adds an integration test to check this behavior
=> Adjust PATCH requests to operate on externalized IRIs

components/agent/src/main/java/org/trellisldp/agent/SimpleAgentService.java, components/constraint-rules/src/main/java/org/trellisldp/constraint/LdpConstraints.java, components/event-serialization/src/main/java/org/trellisldp/event/ActivityStreamMessage.java, core/api/src/main/java/org/trellisldp/api/NoopAccessControlService.java, core/api/src/main/java/org/trellisldp/api/NoopCacheService.java, core/api/src/main/java/org/trellisldp/api/TrellisUtils.java, core/http/src/main/java/org/trellisldp/http/AgentAuthorizationFilter.java, core/http/src/main/java/org/trellisldp/http/CrossOriginResourceSharingFilter.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpFilter.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/main/java/org/trellisldp/http/WebAcFilter.java, core/http/src/main/java/org/trellisldp/http/WebSubHeaderFilter.java, core/http/src/main/java/org/trellisldp/http/core/AcceptDatetime.java, core/http/src/main/java/org/trellisldp/http/core/HttpConstants.java, core/http/src/main/java/org/trellisldp/http/core/Prefer.java, core/http/src/main/java/org/trellisldp/http/core/Range.java, core/http/src/main/java/org/trellisldp/http/core/Slug.java, core/http/src/main/java/org/trellisldp/http/core/TrellisRequest.java, core/http/src/main/java/org/trellisldp/http/core/Version.java, core/http/src/main/java/org/trellisldp/http/impl/BaseLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/HttpUtils.java, core/http/src/main/java/org/trellisldp/http/impl/MementoResource.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/impl/GetHandlerTest.java
Mostly removing the use of Objects::nonNull and Objects::isNull, with a few other bits thrown in.
This PR only covers the stack up through `-http` and ignores all the backends and optional components. They can be handled in separate PRs to avoid crazy levels of line-change too fast.
=> Various small syntax cleanups

components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResource.java, components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceTest.java
Resoves #407
This change applies only to the triplestore-based persistence layer
=> Add config option for LDP ixn model in RDF

core/api/src/main/java/org/trellisldp/api/Resource.java, core/api/src/main/java/org/trellisldp/api/TrellisUtils.java, core/api/src/test/java/org/trellisldp/api/TrellisUtilsTest.java
There is, to my knowledge, no place in the Trellis code in which a `Dataset` might be rolled up concurrently and therefore no need for this extra jazz.
=> No need to guard against concurrency in some paths

components/file/src/main/java/org/trellisldp/file/FileBinary.java, components/file/src/test/java/org/trellisldp/file/FileBinaryServiceTest.java, core/api/src/main/java/org/trellisldp/api/Binary.java, core/api/src/test/java/org/trellisldp/api/BinaryServiceTest.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java
but not enough. This is as good as we can do without `@Context`-injecting actual Servlet types into the `GET` method in `TrellisHttpResource`, which I will do in a follow-on PR that will be considerably more involved. Ultimately I'm going to have to cleanly separate the publishing of headers and body just as we now cleanly separate their computation. In order to do that, I'll need to find/make a completely asynchronous path between `ResourceService::get` and JAX-RS, and we don't have that here yet (viz. the appearance of `IOUtils.copy(binary, out);`, which blocks a container thread for the _whole binary_, quite possibly while waiting for backend data to move around).
=> A little less synchronous

components/webac/src/main/java/org/trellisldp/webac/WebACService.java, core/api/src/main/java/org/trellisldp/api/NoopAccessControlService.java, core/api/src/main/java/org/trellisldp/api/NoopAuditService.java, core/api/src/main/java/org/trellisldp/api/NoopCacheService.java, core/api/src/main/java/org/trellisldp/api/NoopEventService.java, core/api/src/main/java/org/trellisldp/api/NoopMementoService.java, core/api/src/main/java/org/trellisldp/api/NoopNamespaceService.java
Alternative to https://github.com/trellis-ldp/trellis/pull/413
Based on [the CDI spec](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#builtin_qualifiers), leaving the no-op impls as `@Alternative`s and the others as (un-annotated) `@Default`s, we should arrive at the behavior that having any non-no-op impl (e.g. `WebACService` or `JmsPublisher`) on the classpath in a JAR with a `beans.xml` (presumably from build) should prefer the substantive impl, which, IIUC, meets @gregjan's immediate needs.
=> Switching to make no-op impls the CDI @Alternatives

core/vocabulary/src/test/java/org/trellisldp/vocabulary/AbstractVocabularyTest.java
One reason the tests for #424 keep failing is due to the fact that `purl.org` is down (again) and the DCTerms vocabulary cannot be fetched in the `trellis-vocab` tests. This adds a better mechanism for catching those errors.
=> Better vocab error handling

components/webac/src/main/java/org/trellisldp/webac/Authorization.java, components/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, components/webac/src/main/java/org/trellisldp/webac/WebAcService.java, components/webac/src/test/java/org/trellisldp/webac/AuthorizationTest.java, components/webac/src/test/java/org/trellisldp/webac/WebAcFilterTest.java, components/webac/src/test/java/org/trellisldp/webac/WebAcServiceTest.java, core/vocabulary/src/main/java/org/trellisldp/vocabulary/ACL.java
Resolves #9
The logic here assumes that any `acl:origin` defined in an ACL has already been white-listed at the server level. That is, setting `<> acl:origin <https://bad.example.com>` in an ACL document does not suddenly give that Origin access to a resource if the server configuration hasn't already given that Origin access (e.g. via `*` or specifically by name)
=> Add authZ support for acl:origin

components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResource.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java
This removes an unused private method and changes `type` to `RDF.type`, since that's how it's referenced everywhere else in that class.
=> Minor code clean-up

core/http/src/main/java/org/trellisldp/http/core/EtagGenerator.java, core/http/src/main/java/org/trellisldp/http/impl/BaseLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/DeleteHandler.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/HttpUtils.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/impl/GetHandlerTest.java
Resolves #434
This also simplifies the default etag generation code, making it, by default, invariant across response content-types and/or prefer headers, which also makes it considerably more usable by clients.
In addition, should an implementation choose to implement a different mechanism for generating ETags, that is easily done via the standard `ServiceLoader` mechanism.
=> Make ETag generation more flexible

components/app-triplestore/src/main/java/org/trellisldp/app/triplestore/TrellisServiceBundler.java, components/app/build.gradle, components/app/src/test/java/org/trellisldp/app/SimpleServiceBundler.java, components/webdav/src/test/java/org/trellisldp/webdav/AbstractWebDAVTest.java, components/webdav/src/test/java/org/trellisldp/webdav/TrellisWebDAVRequestFilterTest.java, core/http/build.gradle, core/http/src/main/java/module-info.java, core/http/src/main/java/org/trellisldp/http/core/ServiceBundler.java, core/http/src/main/java/org/trellisldp/http/impl/BaseLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/DeleteHandler.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/HttpUtils.java, core/http/src/main/java/org/trellisldp/http/impl/MementoResource.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java, platform/osgi/src/main/java/org/trellisldp/osgi/TrellisServiceBundler.java, platform/webapp/src/main/java/org/trellisldp/webapp/WebappServiceBundler.java
Addresses #441
This moves many of the internally-loaded services into the `ServiceBundler` interface.
With the exception of Commons-RDF, all of the services used in `./core` are now defined in the `ServiceBundler`.
=> Move services into the ServiceBundler interface

components/app-triplestore/src/main/java/org/trellisldp/app/triplestore/AppUtils.java, components/file/src/main/java/module-info.java, components/file/src/main/java/org/trellisldp/file/FileBinaryService.java, components/io-jena/bnd.bnd, components/io-jena/src/main/java/module-info.java, components/io-jena/src/main/java/org/trellisldp/io/JenaIOService.java, components/rdfa/src/main/java/org/trellisldp/rdfa/HtmlSerializer.java, components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, components/webac/src/main/java/org/trellisldp/webac/WebAcService.java, core/api/src/main/java/org/trellisldp/api/DefaultIdentifierService.java, notifications/amqp/bnd.bnd, notifications/amqp/src/main/java/module-info.java, notifications/amqp/src/main/java/org/trellisldp/amqp/AmqpPublisher.java, notifications/amqp/src/main/resources/META-INF/services/org.trellisldp.api.EventService, notifications/amqp/src/test/java/org/trellisldp/amqp/AmqpPublisherTest.java, notifications/jms/bnd.bnd, notifications/jms/build.gradle, notifications/jms/src/main/java/module-info.java, notifications/jms/src/main/java/org/trellisldp/jms/JmsPublisher.java, notifications/jms/src/main/resources/META-INF/services/org.trellisldp.api.EventService, notifications/jms/src/test/java/org/trellisldp/jms/JmsPublisherTest.java, notifications/kafka/bnd.bnd, notifications/kafka/src/main/java/module-info.java, notifications/kafka/src/main/java/org/trellisldp/kafka/KafkaPublisher.java, notifications/kafka/src/main/resources/META-INF/services/org.trellisldp.api.EventService, notifications/kafka/src/test/java/org/trellisldp/kafka/KafkaPublisherTest.java
Resolves #441
This removes the use of the `ServiceLoader` from all of the component libraries in favor of ctor injection. This has resulted in changes to the ctors for the various notification services, which will affect any downstream projects.
One question is whether the notification services should be annotated with `@ApplicationScoped` -- if so, we'll need those no-arg constructors back in place for use with CDI proxies, and we may want to discuss what that would look like.
For the non-notification projects, this was really just a matter of moving the `@Inject` annotation to a different, existing ctor.
=> Remove use of ServiceLoader

components/app-triplestore/src/main/java/org/trellisldp/app/triplestore/TrellisServiceBundler.java, components/app/src/main/java/org/trellisldp/app/DefaultConstraintServices.java, components/app/src/test/java/org/trellisldp/app/DefaultConstraintServicesTest.java, components/app/src/test/java/org/trellisldp/app/SimpleServiceBundler.java
This PR starts using the new `BaseServiceBundler`. It also introduces a `DefaultConstraintServices` class that can be used for `java.util.Collection`-based `ConstraintService` groups.
=> Start using the BaseServiceBundler class

components/test/src/main/java/org/trellisldp/test/MementoResourceTests.java
The Memento resources have headers with a precision of one second,
but there can be rounding issues that lead to a small epsilon of
difference in the various format conversions. This relaxes the memento
datetime tests such that it allows up to 1 second in time discrepancies.
=> Allow a small allowance for rounding discrepancies

components/file/src/main/java/org/trellisldp/file/FileMementoService.java, components/file/src/test/java/org/trellisldp/file/FileMementoServiceTest.java, components/test/src/main/java/org/trellisldp/test/MementoTimeGateTests.java
Resovles #465
For datetime negotiation requests that ask for a memento that predates
any existing memento, the Memento specification requires that the first
available Memento resource be returned.
https://tools.ietf.org/html/rfc7089#section-4.5.3
=> Fix TimeGate/Memento handling

auth/basic/src/main/java/module-info.java, components/file/src/main/java/module-info.java, components/io-jena/src/main/java/module-info.java, components/test/src/main/java/module-info.java, components/triplestore/src/main/java/module-info.java, components/webac/src/main/java/module-info.java, components/webdav/src/main/java/module-info.java, core/http/src/main/java/module-info.java, notifications/amqp/src/main/java/module-info.java, notifications/jms/src/main/java/module-info.java, notifications/kafka/src/main/java/module-info.java
The SLF4J project now publishes the `Automatic-Module-Name` header, so we can adjust the JDK11 configurations to use that.
=> Update slf4j module definition

core/api/src/main/java/org/trellisldp/api/NoopAuditService.java, core/api/src/main/java/org/trellisldp/api/NoopEventService.java
Quarkus doesn't like `@ApplicationScoped` beans that have the `final` keyword. This just removes those keywords.
=> Remove final keyword to no-op services

build.gradle, components/agent/src/main/java/module-info.java, components/audit/src/main/java/module-info.java, components/constraint-rules/src/main/java/module-info.java, components/event-serialization/build.gradle, components/event-serialization/src/main/java/module-info.java, components/file/src/main/java/module-info.java, components/io-jena/src/main/java/module-info.java, components/namespaces/src/main/java/module-info.java, components/rdfa/src/main/java/module-info.java, components/triplestore/src/main/java/module-info.java, components/webac/src/main/java/module-info.java, core/api/src/main/java/module-info.java, core/http/src/main/java/module-info.java, notifications/amqp/src/main/java/module-info.java
resolves #498
adds several missing requires to module-infos
corrects split package for javax.xml.bind by substituting jakarta.xml.bind-api with jaxb.api and updates jaxb.api version
=> Add several requires to module-infos

components/dropwizard/src/main/java/org/trellisldp/dropwizard/AbstractTrellisApplication.java, components/webac/src/main/java/org/trellisldp/webac/WebAcService.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceTest.java
Takes out database initialization of the root ACL, leaving WebAC considerations outside of persistence backend initialization. Instead there is a default ACL that permits all actions by all agents, i.e. no restrictions. This is a single Authorization that is held in a static variable.
=> Moves from ACL database initialization to a permissive default root ACL

components/file/src/main/java/org/trellisldp/file/FileBinary.java, components/file/src/test/java/org/trellisldp/file/FileBinaryServiceTest.java, components/test/src/main/java/org/trellisldp/test/InMemoryBinaryService.java, components/test/src/test/java/org/trellisldp/test/InMemoryBinaryServiceTest.java, core/api/src/main/java/org/trellisldp/api/Binary.java, core/api/src/test/java/org/trellisldp/api/BinaryServiceTest.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java, core/http/src/test/java/org/trellisldp/http/impl/GetHandlerTest.java
This changeset removes one level of asynchrony from the path between binary data and HTTP by switching the signatures of `Binary::getContent` from `CompletionStage<InputStream>` to `InputStream`. This is appropriate because the only use `trellis-http` makes use of the `CompletionStage<InputStream>` is to immediately call `toCompletableFuture().join()` on it, which is absurd. We should rely going forward on the practice we've developed of answering HTTP requests using `@Suspended` by getting a `CompletionStage` from one or more of `ResourceService`, `MementoService`, `BinaryService`, etc.. The types _inside_ those `CompletionStage`s would themselves feature methods that return ordinary (non-promise/future) types. This changeset causes that to be the case.
=> Less asynchrony for Binary::getContent

components/file/src/main/java/org/trellisldp/file/FileMementoService.java, components/file/src/main/java/org/trellisldp/file/FileUtils.java, components/file/src/test/java/org/trellisldp/file/FileMementoServiceTest.java, components/file/src/test/java/org/trellisldp/file/FileUtilsTest.java
Resolves #496
This method is not used in the HTTP layer, but it provides a mechanism
for someone to use it in a separate JAX-RS component. The existing
MementoService methods remain unchanged.
=> Add delete method to FileMementoService

core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java
The `@Provider` annotation is not relevant for `@Path`-annotated JAX-RS resources. Neither the JAX-RS runtime nor the CDI environment need it. It should be removed.
=> Remove Provider annotation

components/app/src/test/java/org/trellisldp/app/CDIServiceBundlerTest.java, components/app/src/test/java/org/trellisldp/app/TestServices.java, core/api/src/main/java/org/trellisldp/api/NoopImplementation.java
I have found that, with Quarkus, the CDI injection mechanism sees the no-op service implementation beans as if they have both `@Default` and `@All` qualifiers when viewed in the context of ctor injection. E.g.:
```java
@Inject
public JenaIOService(final NamespaceService namespaceService, ...) { ... }
```
leading to ambiguous dependency resolution errors. This change expands the `@Target` types of the `@NoopImplementation` stereotype and also adds an explicit `@Priority` annotation.
=> Adjust NoopImpl annotations

platform/bom/build.gradle
This is very minor: the `trellis-reactive` artifact is currently missing from the `trellis-bom`. This adds that subproject to make it easier to use in downstream apps.
=> Add trellis-reactive to bom artifact

components/file/src/main/java/org/trellisldp/file/FileBinaryService.java, components/file/src/main/java/org/trellisldp/file/FileMementoService.java, components/namespaces/src/main/java/org/trellisldp/namespaces/JsonNamespaceService.java, platform/app-mp-triplestore/build.gradle, platform/app-mp-triplestore/src/main/resources/META-INF/microprofile-config.properties
The `trellis-namespaces` and `trellis-file` components do not currently have CDI annotations. This adds those annotations.
=> Add cdi annotation to namespaces, file components

build.gradle, notifications/event-jsonb/bnd.bnd, notifications/event-jsonb/build.gradle, notifications/event-jsonb/src/main/java/module-info.java, notifications/event-jsonb/src/main/java/org/trellisldp/event/jsonb/ActivityStreamMessage.java, notifications/event-jsonb/src/main/java/org/trellisldp/event/jsonb/DefaultActivityStreamService.java, notifications/event-jsonb/src/main/java/org/trellisldp/event/jsonb/package-info.java, notifications/event-jsonb/src/main/resources/META-INF/beans.xml, notifications/event-jsonb/src/main/resources/META-INF/services/org.trellisldp.api.ActivityStreamService, notifications/event-jsonb/src/test/java/org/trellisldp/event/jsonb/DefaultActivityStreamServiceTest.java, platform/bom/build.gradle, platform/openliberty/build.gradle, platform/quarkus/build.gradle, settings.gradle
Resolves #524
This is very similar to the existing trellis-event component except that
it doesn't depend on Jackson. This will generally be used by
microprofile-based systems.
=> Add json-b based event serializer

core/api/src/main/java/org/trellisldp/api/NoopActivityStreamService.java, core/api/src/test/java/org/trellisldp/api/NoopActivityStreamServiceTest.java, notifications/kafka/src/main/java/org/trellisldp/kafka/KafkaEventService.java, notifications/kafka/src/test/java/org/trellisldp/kafka/KafkaEventServiceTest.java, notifications/reactive/src/main/java/org/trellisldp/reactive/ReactiveEventService.java, notifications/reactive/src/test/java/org/trellisldp/reactive/ReactiveEventServiceTest.java
Resolves #537
In certain CDI environments, especially Quarkus, having no-arg
constructors is needed for creating proxy-able beans prior to actual
injection.
As such, this adds no-arg ctors to the -reactive and -kafka event
service implementations and also introduces a NoopActivityStreamService
that can be used by those ctors.
=> Add no-arg constructors for CDI-managed beans

components/app/build.gradle
This adjusts the dependency scopes to ensure that trellis-vocabulary
ends up in the right runtime scope. It also moves the cdi dependency to
api scope, since that should also be defined there. The mp-config
dependency is removed since it is not used.
=> Adjust dependency scopes for trellis-app

components/triplestore/build.gradle, platform/quarkus/build.gradle
Because RDFConnection is part of the public API, the jena-rdfconnection
dependency should be at the api (instead of implementation) scope.
=> Adjust scope of Jena dependencies

build.gradle
Instead of having each component "opting-in" to jacoco analysis (which is easy to forget), components can now opt-out
=> Rework JaCoCo configuration

buildtools/src/main/resources/pmd/pmd.xml, components/test/src/main/java/org/trellisldp/test/AuditTests.java, components/test/src/main/java/org/trellisldp/test/InMemoryBinaryService.java, components/test/src/main/java/org/trellisldp/test/InMemoryResourceService.java, components/test/src/main/java/org/trellisldp/test/LdpBasicContainerTests.java, components/test/src/main/java/org/trellisldp/test/LdpBinaryTests.java, components/test/src/main/java/org/trellisldp/test/LdpDirectContainerTests.java, components/test/src/main/java/org/trellisldp/test/LdpIndirectContainerTests.java, components/test/src/main/java/org/trellisldp/test/LdpRdfTests.java, components/test/src/main/java/org/trellisldp/test/MementoBinaryTests.java, components/test/src/main/java/org/trellisldp/test/MementoResourceTests.java, components/test/src/main/java/org/trellisldp/test/ResourceServiceTests.java
Most of the Graph and Dataset objects in the trellis-test codebase are
not closed. This updates those tests to close the resources.
=> Close resources after use in test suite

core/api/src/test/java/org/trellisldp/api/DefaultIdentifierServiceTest.java, core/api/src/test/java/org/trellisldp/api/NoopEventSerializationServiceTest.java, core/api/src/test/java/org/trellisldp/api/NoopResourceServiceTest.java, core/api/src/test/java/org/trellisldp/api/ResourceServiceTest.java, core/api/src/test/java/org/trellisldp/api/TrellisUtilsTest.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceAdminTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceBaseUrlTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceNoAgentTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceUserTest.java, core/http/src/test/java/org/trellisldp/http/core/PreferTest.java, core/http/src/test/java/org/trellisldp/http/core/SlugTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java, core/http/src/test/java/org/trellisldp/http/impl/DeleteHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/GetHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/HttpUtilsTest.java, core/http/src/test/java/org/trellisldp/http/impl/MementoResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/OptionsHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java, core/vocabulary/src/test/java/org/trellisldp/vocabulary/AbstractVocabularyTest.java
There are a lot of line changes here, but it's all just reformatting test code to address PMD warnings. Primarily it consists of closing `AutoClosable` resources and factoring repeated strings into variables.
This is also just for the code in `./core`. Other components will be addressed separately.
=> Address PMD warnings in test code for core components

core/http/src/main/java/org/trellisldp/http/TrellisHttpFilter.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/main/java/org/trellisldp/http/core/HttpConstants.java, core/http/src/main/java/org/trellisldp/http/core/Prefer.java, core/http/src/main/java/org/trellisldp/http/impl/BaseLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/DeleteHandler.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/HttpUtils.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/OptionsHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceAdminTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceBaseUrlTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceNoAgentTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/core/PreferTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java, core/http/src/test/java/org/trellisldp/http/impl/DeleteHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/GetHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/HttpUtilsTest.java, core/http/src/test/java/org/trellisldp/http/impl/OptionsHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java
Resolves #535
This generalizes the graph extension mechanism. By default, the
`acl` => `trellis:PreferAccessControl` mapping remains in place, but
this can be overridden/extended by configuration.
Note: this needs some more testing and refinement before merging, but this appears to work as advertised.
=> Adjust named graph extension mechanism

components/test/src/main/java/org/trellisldp/test/LdpBasicContainerTests.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/main/java/org/trellisldp/http/core/HttpConstants.java, core/http/src/main/java/org/trellisldp/http/impl/DeleteHandler.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/HttpUtils.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/OptionsHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/GetHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java
Resolves #564
This feature is enabled by default, but it can be disabled by setting the `trellis.http.patch.create` property to `false`.
=> Add support for resource creation via PATCH

.travis.yml, build.gradle, buildtools/src/main/resources/docker/publishToDockerHub.sh, platform/quarkus/build.gradle, platform/quarkus/src/main/docker/Dockerfile.jvm, platform/quarkus/src/main/java/org/trellisldp/quarkus/SimpleNamespaceService.java, platform/quarkus/src/main/resources/application.properties, platform/quarkus/src/test/java/org/trellisldp/quarkus/ApplicationTest.java, platform/quarkus/src/test/java/org/trellisldp/quarkus/SimpleNamespaceServiceTest.java
This adds a docker configuration for the quarkus-based image and pushes that image to docker hub on successful builds.
This also adds trellis-related configuration values to the `application.properties` file, making these values easier to override by users of the docker image.
=> Add Docker configuration for quarkus

components/dropwizard/src/main/java/org/trellisldp/dropwizard/AbstractTrellisApplication.java, components/dropwizard/src/main/java/org/trellisldp/dropwizard/config/AuthConfiguration.java, components/dropwizard/src/test/java/org/trellisldp/dropwizard/config/TrellisConfigurationTest.java, components/dropwizard/src/test/resources/config1.yml, components/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, components/webac/src/test/java/org/trellisldp/webac/WebAcFilterTest.java
Resolves #575
Adding this support is driven by configuration and is entirely optional
=> Support scope attribute in WWW-Authenticate header

platform/quarkus/src/main/docker/Dockerfile.jvm
This is a smaller docker base image that doesn't contain all the JMX extras
=> Use a plain alpine-linux docker base image

auth/basic/build.gradle, auth/oauth/build.gradle, build.gradle, components/app-triplestore/build.gradle, components/app/build.gradle, components/audit/build.gradle, components/cache/build.gradle, components/cdi/build.gradle, components/constraint-rules/build.gradle, components/dropwizard/build.gradle, components/file/build.gradle, components/io-jena/build.gradle, components/namespaces/build.gradle, components/rdfa/build.gradle, components/test/build.gradle, components/triplestore/build.gradle, components/webac/build.gradle, components/webdav/build.gradle, core/api/build.gradle, core/http/build.gradle, core/vocabulary/build.gradle, notifications/amqp/build.gradle, notifications/event-jackson/build.gradle, notifications/jms/build.gradle, notifications/kafka/build.gradle, notifications/reactive/build.gradle, platform/openliberty/build.gradle, platform/osgi/build.gradle, platform/quarkus/build.gradle, platform/server/build.gradle
There are a lot of line changes here but not much going on.
The use of `compile` and `testCompile` scopes are deprecated and have been changed to `implementation` and `testImplementation`
Similarly, `runtime` and `testRuntime` => `runtimeClasspath` and `testRuntimeClasspath`
Those changes will be needed once we move to Gradle 6.
Furthermore, the declaration of these dependences has been normalized (removing unneeded parens)
=> Update gradle dependency scopes

components/test/build.gradle
JUnit should have api scope, since there are JUnit annotations on public classes/methods. Also, junit engine should have implementation, rather than runtime, scope.
=> Adjust junit dependency scope for test module

auth/jwt/bnd.bnd, auth/jwt/build.gradle, auth/jwt/src/main/java/module-info.java, auth/jwt/src/main/java/org/trellisldp/auth/jwt/JwtAuthFilter.java, auth/jwt/src/main/java/org/trellisldp/auth/jwt/WebIdPrincipal.java, auth/jwt/src/main/java/org/trellisldp/auth/jwt/WebIdSecurityContext.java, auth/jwt/src/main/java/org/trellisldp/auth/jwt/package-info.java, auth/jwt/src/main/resources/META-INF/beans.xml, auth/jwt/src/test/java/org/trellisldp/auth/jwt/JwtAuthFilterTest.java, auth/jwt/src/test/java/org/trellisldp/auth/jwt/WebIdPrincipalTest.java, auth/jwt/src/test/java/org/trellisldp/auth/jwt/WebIdSecurityContextTest.java, auth/jwt/src/test/resources/logback.xml, build.gradle, core/http/src/main/java/org/trellisldp/http/core/HttpSession.java, core/http/src/test/java/org/trellisldp/http/core/HttpSessionTest.java, platform/bom/build.gradle, platform/karaf/src/main/resources/features.xml, platform/osgi/build.gradle, platform/osgi/src/test/java/org/trellisldp/osgi/OSGiTest.java, platform/quarkus/build.gradle, platform/quarkus/src/main/resources/application.properties, settings.gradle
Resolves #508
This adds a microprofile-based authentication module. Effectively, it's a JAX-RS filter that takes the injected `JsonWebToken` and puts it into a `SecurityContext` that ensures that the `Principal` name is a WebID.
This module is, effectively, a microprofile version of `trellis-auth-oauth`
=> Implement microprofile-based authentication module

components/test/src/main/java/org/trellisldp/test/AuditTests.java, components/test/src/main/java/org/trellisldp/test/LdpRdfTests.java, components/test/src/main/java/org/trellisldp/test/MementoResourceTests.java, components/test/src/main/java/org/trellisldp/test/ResourceServiceTests.java, components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java
Resolves #595
Most of this PR adjusts the test suite to also handle implementations that may choose not to add the LDP type triple(s).
=> Add LDP type triples by default

auth/basic/build.gradle, auth/jwt/build.gradle, auth/oauth/build.gradle, build.gradle, components/app/build.gradle, components/cdi/build.gradle, components/dropwizard/build.gradle, components/webdav/build.gradle, core/api/build.gradle, core/http/build.gradle, core/vocabulary/build.gradle, platform/openliberty/build.gradle, platform/osgi/build.gradle, platform/quarkus/build.gradle, platform/server/build.gradle
According to the [gradle documentation](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph), we should be using `runtimeOnly` instead of `runtimeClasspath` when defining dependency scopes.
=> Adjust runtime dependency scope

build.gradle, gradle/wrapper/gradle-wrapper.properties, platform/bom/build.gradle, settings.gradle
Resolves #625 
This upgrades the Trellis build to gradle 6. With this commit, gradle 5 will no longer be supported.
=> Upgrade to gradle6

components/dropwizard/src/main/java/org/trellisldp/dropwizard/config/TrellisConfiguration.java, components/dropwizard/src/test/java/org/trellisldp/dropwizard/SimpleServiceBundler.java, components/dropwizard/src/test/java/org/trellisldp/dropwizard/config/TrellisConfigurationTest.java, components/dropwizard/src/test/resources/config1.yml, components/dropwizard/src/test/resources/trellis-config.yml, components/io-jena/src/main/java/org/trellisldp/io/JenaIOService.java, components/io-jena/src/test/java/org/trellisldp/io/JenaIOServiceTest.java, components/test/src/main/java/org/trellisldp/test/TestUtils.java, core/api/src/main/java/org/trellisldp/api/IOService.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/MementoResource.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, platform/dropwizard/src/main/java/org/trellisldp/app/triplestore/TrellisServiceBundler.java, platform/server/src/docker/config.yml
Resolves #651
This changes the api for `IOService::write`, adding a `context` parameter, which is a breaking change for the API. This also adds a configuration value for controlling whether to use relative IRIs in Turtle output (default=false). The configuration property is `trellis.io.relative-iris`. A corresponding configuration value is added to the dropwizard config object.
=> Add support for relative IRIs

build.gradle, settings.gradle
The dependabot integration will work much better if the `settings.gradle` file uses this (arguably more standard) format.
=> Adjust settings file format

components/file/src/main/java/org/trellisldp/file/FileMementoService.java, components/file/src/test/java/org/trellisldp/file/FileMementoServiceTest.java, core/http/src/main/java/org/trellisldp/http/core/HttpConstants.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java, platform/dropwizard/src/main/java/org/trellisldp/app/triplestore/AppConfiguration.java, platform/dropwizard/src/main/java/org/trellisldp/app/triplestore/TrellisServiceBundler.java, platform/dropwizard/src/test/java/org/trellisldp/app/triplestore/TrellisConfigurationTest.java, platform/dropwizard/src/test/resources/config1.yml, platform/quarkus/build.gradle, platform/quarkus/src/main/resources/application.properties
Resolves #681
This adds two new configuration properties: 
`trellis.http.versioning` -- this accepts true/false values (default=true) and controls whether the HTTP layer takes responsibility for creating Mementos
`trellis.file.versioning` -- this accepts true/false values (default=true) and controls whether the FileMemento component is enabled
=> Make versioning more configurable

core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/main/java/org/trellisldp/http/impl/OptionsHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/OptionsHandlerTest.java
Resolves #705
Now, responses to OPTIONS requests have nothing to do with the presence/absence or LDP type of a resource, which is in line with how (esp. JavaScript) clients use OPTIONS requests.
=> Adjust handling of OPTIONS requests

components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAV.java
This limits certain classes of vulnerabilities when processing XML documents.
=> Tighten down XML parsing configuration for WebDAV

core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java
This makes it possible to be more precise when applying constraints to extension graphs
=> Improve metadata graph constraint handling

components/test/src/main/java/org/trellisldp/test/LdpRdfTests.java, components/test/src/main/resources/org/trellisldp/test/shex.jsonld, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, platform/quarkus/build.gradle
In multi-threaded contexts, JSON-LD input streams can be prematurely closed. This buffers those streams in a better structure for incoming RDF.
=> Better JSON-LD support with Quarkus

platform/quarkus/build.gradle
This dramatically simplifies how Quarkus is built. It does mean that `quarkusDev` doesn't work as well, but this will be a net improvement.
=> Rework quarkus build structure

auth/basic/src/main/java/org/trellisldp/auth/basic/BasicAuthFilter.java, auth/basic/src/test/java/org/trellisldp/auth/basic/BasicAuthFilterTest.java, auth/oauth/src/main/java/org/trellisldp/auth/oauth/OAuthFilter.java, auth/oauth/src/test/java/org/trellisldp/auth/oauth/OAuthFilterTest.java, components/dropwizard/src/main/java/org/trellisldp/dropwizard/AbstractTrellisApplication.java, components/dropwizard/src/main/java/org/trellisldp/dropwizard/TrellisUtils.java, components/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, components/webac/src/test/java/org/trellisldp/webac/WebAcFilterTest.java, components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAVRequestFilter.java, components/webdav/src/test/java/org/trellisldp/webdav/TrellisWebDAVRequestFilterTest.java, components/webdav/src/test/java/org/trellisldp/webdav/WebDAVNoBaseUrlTest.java, components/webdav/src/test/java/org/trellisldp/webdav/WebDAVTest.java, core/http/src/main/java/org/trellisldp/http/CacheControlFilter.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpFilter.java, core/http/src/main/java/org/trellisldp/http/WebSubHeaderFilter.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/CacheControlFilterTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceAdminTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceBaseUrlTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceNoAgentTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceUserTest.java, core/http/src/test/java/org/trellisldp/http/WebSubHeaderFilterTest.java
Resolves: #819
JAX-RS providers should have a single no-arg constructor in order to be supported across JAX-RS implementations
=> Use a single no-arg ctor for JAX-RS Providers

.github/workflows/ci-config.yml, platform/osgi/build.gradle
The OSGi tests are now suitably stable for Java 11
=> Use Java11 for OSGi tests

.github/workflows/cd-config.yml, .github/workflows/ci-config.yml, .travis.yml, build.gradle
PMD analysis adds quite a bit of overhead/time to the build. This disables analysis from the default build but keeps it available if enabled via `gradle build -P pmd`
=> Disable pmd analysis by default

components/triplestore/src/main/java/org/trellisldp/triplestore/RDFConnectionProvider.java, components/triplestore/src/test/java/org/trellisldp/triplestore/RDFConnectionProviderTest.java, platform/openliberty/src/main/java/org/trellisldp/openliberty/TrellisServiceSupplier.java, platform/quarkus/src/main/java/org/trellisldp/quarkus/ServiceProviders.java
This adds a RDFConnection producer for CDI apps such as quarkus and openliberty, which makes the triplestore layer more swappable for other backends, which will make things more flexible for #837
=> Add RDFConnectionProvider class

build.gradle
It turns out that `property.hasProperty("pmd")` is always true
=> Adjust pmd configuration for task graph

core/vocabulary/src/test/java/org/trellisldp/vocabulary/TrellisTest.java
Now that the new Trellis vocabulary has been published, we can do strict enforcement on the terms.
=> Make vocab testing strict

.travis.yml
The sonar analysis requires the `-Ptriplestore` flag (or a fully-functional database)
=> Adjust CI for sonar analysis

.github/workflows/ci-config.yml, README.md, build.gradle
This removes the use of coveralls for code coverage stats, relying instead on Sonar
=> Use sonar for coverage stats

auth/webac/src/main/java/org/trellisldp/webac/AuthorizedModes.java, auth/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, auth/webac/src/main/java/org/trellisldp/webac/WebAcService.java, auth/webac/src/test/java/org/trellisldp/webac/WebAcFilterTest.java
=> Effective ACL should point to correct location

core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java
Resolves #925
This makes the content-type comparison considerably more robust, ignoring any header parameters (such as `charset`)
=> Support PATCH with content-type headers that contain a charset parameter

components/jdbc/src/main/java/org/trellisldp/jdbc/DBWrappedMementoService.java, components/jdbc/src/main/resources/db/migration/V0.6__Trellis.sql, components/jdbc/src/main/resources/org/trellisldp/jdbc/migrations.yml, components/jdbc/src/test/java/org/trellisldp/jdbc/DBWrappedMementoServiceTest.java, core/http/src/main/java/org/trellisldp/http/core/HttpConstants.java, core/http/src/main/java/org/trellisldp/http/impl/DeleteHandler.java, core/http/src/test/java/org/trellisldp/http/impl/DeleteHandlerTest.java
This adds a `binary` table to the JDBC component structure, makes binary deletes configurable and improves support for no-op Memento service in the JDBC component.
=> Support binary deletes, add binary table to jdbc component

components/jdbc/src/main/resources/db/migration/V0.6__Trellis.sql, components/jdbc/src/main/resources/org/trellisldp/jdbc/migrations.yml, core/http/src/main/java/org/trellisldp/http/impl/DeleteHandler.java
The binary table should have an identifier that is decoupled from the resource table
=> Adjust binary table columns

components/jdbc/src/main/resources/db/migration/V0.6__Trellis.sql, components/jdbc/src/main/resources/org/trellisldp/jdbc/migrations.yml
The name `binary` doesn't work so well as a table name.
=> Change name of non-RDF table

components/test/src/main/java/org/trellisldp/test/ResourceServiceTests.java
In the event that an implementation creates LDP-BC resources when an LDP-C interaction model is part of the incoming metadata
=> Allow more flexibility for LDP-C creation

platform/openliberty/build.gradle, settings.gradle
The 3.0 version of the OpenLiberty plugin has been available for some time, and it would be good to upgrade to use it.
=> Update OpenLiberty plugin to 3.0

auth/basic/src/main/java/org/trellisldp/auth/basic/Credentials.java, auth/oauth/src/main/java/org/trellisldp/oauth/OAuthFilter.java, auth/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, components/file/src/main/java/org/trellisldp/file/FileNamespaceService.java, components/file/src/main/java/org/trellisldp/file/FileUtils.java, components/jdbc/src/main/java/org/trellisldp/jdbc/DBNamespaceService.java, core/common/src/main/java/org/trellisldp/common/AcceptDatetime.java, core/common/src/main/java/org/trellisldp/common/Forwarded.java, core/common/src/main/java/org/trellisldp/common/Range.java, core/common/src/main/java/org/trellisldp/common/Slug.java, core/common/src/main/java/org/trellisldp/common/Version.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java
This reviews the log levels for various events with an emphasis on keeping PII out of log entries under normal operation.
=> Review log levels

core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java
Extension graph events for containers report non-container URLs. This ensures that events for containers use the correct URL.
=> Use correct URL for extension graph update events

platform/bom/build.gradle
The trellis-common module is missing from the trellis-bom component
=> include trellis-common in BOM

auth/webac/src/main/java/org/trellisldp/webac/WebAcService.java, auth/webac/src/test/java/org/trellisldp/webac/WebAcServiceTest.java
=> WebACL default statements do not require acl:accessTo predicates

platform/osgi/build.gradle, platform/osgi/src/test/java/org/trellisldp/osgi/OSGiTest.java
This allows the OSGi tests to use a JDK 11 target
=> Adjust OSGi tests for JDK 11

build.gradle
This adjusts the `docs` task to work with Java 11
=> Fix docs task for java11

core/api/src/main/java/org/trellisldp/api/Metadata.java, core/api/src/test/java/org/trellisldp/api/MetadataTest.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java
=> Make Metadata class more extensible

components/jena/src/main/java/org/trellisldp/jena/JenaIOService.java
Reverts trellis-ldp/trellis#1123
It turns out that Trellis already supports unicode characters in paths. The problem had more to do with how cURL handles unicode characters.
=> Revert "Better support for Unicode paths"

core/common/src/main/java/org/trellisldp/common/TrellisRequest.java, core/common/src/test/java/org/trellisldp/common/TrellisRequestTest.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java
Resolves #1125
This makes it possible for clients to send multiple Link headers while not having to worry about ordering. Only the first _relevant_ LDP link header will be used by the HTTP layer.
=> Improved support for Link header handling

core/common/build.gradle, core/common/src/main/java/org/trellisldp/common/HttpConstants.java, core/common/src/main/java/org/trellisldp/common/Slug.java, core/common/src/test/java/org/trellisldp/common/SlugTest.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpFilter.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpFilterTest.java, core/http/src/test/resources/logback-test.xml
Resolves #1130
This prohibits unwise characters in paths and also removes them from incoming Slug headers
=> Disallow unwise characters

build.gradle
=> The apiguardian version does not need to be managed independently of JUnit

.github/workflows/cd-config.yml, .github/workflows/ci-config.yml, .github/workflows/codeql-analysis.yml
This will make version management much easier.
=> Use major versions for GH action dependencies

components/test/src/main/java/org/trellisldp/test/LdpRdfTests.java, core/common/src/main/java/org/trellisldp/common/HttpConstants.java, core/common/src/main/java/org/trellisldp/common/Slug.java, core/common/src/main/java/org/trellisldp/common/TrellisRequest.java, core/common/src/test/java/org/trellisldp/common/SlugTest.java, core/common/src/test/java/org/trellisldp/common/TrellisRequestTest.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpFilter.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpFilterTest.java
=> Improve support for reserved characters

build.gradle, components/test/build.gradle, components/test/src/main/java/module-info.java, components/test/src/main/java/org/trellisldp/test/AbstractApplicationAuthTests.java, components/test/src/main/java/org/trellisldp/test/AuditTests.java, components/test/src/main/java/org/trellisldp/test/EventTests.java, components/test/src/main/java/org/trellisldp/test/TestUtils.java
Using smallrye-jwt is much better for token generation/validation. This removes the dependency on java-jjwt
=> Completely remove dependency on jjwt

components/test/src/main/java/org/trellisldp/test/LdpBinaryTests.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/GetHandlerTest.java
Binary content negotiation for RDF will now redirect to the description resource URL.
=> Redirect on binary content negotiation

components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAV.java, components/webdav/src/main/java/org/trellisldp/webdav/impl/WebDAVUtils.java, core/api/src/main/java/org/trellisldp/api/Notification.java, core/common/src/main/java/org/trellisldp/common/SimpleNotification.java, core/common/src/test/java/org/trellisldp/common/SimpleNotificationTest.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, notifications/jackson/src/main/java/org/trellisldp/notification/jackson/ActivityStreamMessage.java, notifications/jackson/src/test/java/org/trellisldp/notification/jackson/DefaultNotificationSerializationServiceTest.java, notifications/jsonb/src/main/java/org/trellisldp/notification/jsonb/ActivityStreamMessage.java, notifications/jsonb/src/test/java/org/trellisldp/notification/jsonb/DefaultNotificationSerializationServiceTest.java
Use a trellis-specific predicate for resource state in notifications
=> Refine notification API

components/test/src/main/java/org/trellisldp/test/LdpBinaryTests.java, core/common/src/main/java/org/trellisldp/common/SimpleNotification.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/GetHandlerTest.java
This removes content negotiation on LDP-NR resources, which is not something that LDP describes.
=> Remove description negotiation on LDP-NRs

core/http/src/main/java/org/trellisldp/http/impl/DeleteHandler.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java
This adjusts the behavior of LDP-NR resources such that they can no longer be the target of a PATCH. The associated description _can_ be the target of a PATCH
=> Restrict PATCH to binary descriptions

core/common/src/main/java/org/trellisldp/common/HttpConstants.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java
This will include a `Vary: Origin` header to help with CORS issues when browsing from multiple domains.
=> Include a vary: origin header

notifications/amqp/src/main/java/org/trellisldp/amqp/AmqpNotificationService.java, notifications/jms/src/main/java/org/trellisldp/jms/JmsNotificationService.java, notifications/kafka/src/main/java/org/trellisldp/kafka/KafkaNotificationService.java
Related to #1277
The features provided by these projects can all be achieved with `trellis-reactive`
=> Deprecate notification connectors

core/api/src/main/java/org/trellisldp/api/Session.java, core/api/src/test/java/org/trellisldp/api/SessionTest.java
This makes it possible to represent client identifiers in `Session` data structures.
=> Support client identifiers in session data structures

core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java
This addresses a bug for which content-negotiated LDP-NRs should return a 406 Not Acceptable error when an RDF syntax is requested.
In other words, given an LDP-NR at `/image`:
```http
GET /image
Accept: text/turtle
```
Should return a `406 Not Acceptable`
```http
GET /image
Accept: text/turtle, image/*
```
Should return a `200 OK`
=> Use correct content negotiation for NonRDF resources

core/http/src/main/java/org/trellisldp/http/CacheControlFilter.java, core/http/src/test/java/org/trellisldp/http/CacheControlFilterTest.java
This sets `Cache-Control: private` for authenticated requests.
=> Add private cache control with authenticated requests

core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java
When patching to create a resource in a container that doesn't (yet) exist, the parent reference is missing. This fixes that reference.
=> Include parent reference for PATCH-to-create

build.gradle, components/rdfa/src/main/java/org/trellisldp/rdfa/DefaultRdfaWriterService.java, components/rdfa/src/main/resources/META-INF/services/org.trellisldp.api.RDFaWriterService, components/rdfa/src/test/java/org/trellisldp/rdfa/DefaultRdfaWriterServiceTest.java, components/test/src/main/java/org/trellisldp/test/LdpRdfTests.java
=> Better RDFa template lookup
