.travis.yml, README.md, build.gradle
=> Add coveralls reporting

trellis-app/build.gradle
See https://github.com/trellis-ldp/trellis/issues/58#issuecomment-372062967
=> removes redundant artifacts

trellis-http/src/main/java/org/trellisldp/http/impl/DeleteHandler.java, trellis-http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, trellis-http/src/main/java/org/trellisldp/http/impl/PostHandler.java, trellis-http/src/main/java/org/trellisldp/http/impl/PutHandler.java, trellis-http/src/test/java/org/trellisldp/http/impl/DeleteHandlerTest.java, trellis-http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java, trellis-http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, trellis-http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java
=> Clarify HTTP semantics of ResourceService responses

components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java
@ajs6f this should fix the rest of the tests.
=> Fix the rest of the tests

components/test/src/main/java/org/trellisldp/test/ResourceServiceTests.java, components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java, core/api/src/main/java/org/trellisldp/api/ImmutableDataService.java, core/api/src/main/java/org/trellisldp/api/JoiningResourceService.java, core/api/src/main/java/org/trellisldp/api/MutableDataService.java, core/api/src/main/java/org/trellisldp/api/ResourceService.java, core/api/src/test/java/org/trellisldp/api/JoiningResourceServiceTest.java, core/http/src/main/java/org/trellisldp/http/MultipartUploader.java, core/http/src/main/java/org/trellisldp/http/impl/DeleteHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractLdpResourceTest.java, core/http/src/test/java/org/trellisldp/http/CORSResourceTest.java, core/http/src/test/java/org/trellisldp/http/LdpForbiddenResourceTest.java, core/http/src/test/java/org/trellisldp/http/LdpUnauthorizedResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/DeleteHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java
Resolves https://github.com/trellis-ldp/trellis/issues/91
=> Adding container parameter to mutating code paths

platform/linux/README.md
=> documents ALPN configuration for Java

components/io-jena/src/main/java/org/trellisldp/io/JenaIOService.java
=> adds explicit jena.graph.Graph reference for PATCH return value

components/app-triplestore/src/main/java/org/trellisldp/app/triplestore/TrellisApplication.java, components/app-triplestore/src/test/resources/config1.yml, components/app/README.md, components/app/src/main/java/org/trellisldp/app/config/AssetConfiguration.java, components/app/src/test/java/org/trellisldp/app/config/TrellisConfigurationTest.java, components/app/src/test/resources/config1.yml, components/rdfa/src/main/resources/org/trellisldp/rdfa/resource-table.mustache, platform/linux/README.md
=> adds optional configuration for html template

core/http/src/main/java/org/trellisldp/http/LdpResource.java, core/http/src/test/java/org/trellisldp/http/LdpResourceTest.java
=> Add support for asynchronous HTTP

build.gradle
@ajs6f This is the change I'm thinking of. Does this work in your environment?
=> Minor changes to the gradle dependency declarations

build.gradle, core/http/src/main/java/org/trellisldp/http/impl/BaseLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/main/java/org/trellisldp/http/impl/RdfUtils.java, core/http/src/main/java/org/trellisldp/http/impl/TrellisDataset.java
The `junit-platform-launcher` stuff is a small fix so that JUnit 5 tests will run in Eclipse.
=> A few more tweaks for CDI and some new logging

core/http/src/main/java/org/trellisldp/http/LdpResource.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/main/java/org/trellisldp/http/impl/RdfUtils.java, core/http/src/test/java/org/trellisldp/http/impl/GetHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/RdfUtilsTest.java
=> Make binary handling asynchronous

core/http/src/main/java/org/trellisldp/http/LdpResource.java
This uses the CDI singleton annotation, which, given that we want to support CDI, is preferred.
=> Use CDI annotation

components/app/src/main/java/org/trellisldp/app/AbstractTrellisApplication.java, components/app/src/test/java/org/trellisldp/app/SimpleServiceBundler.java, components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java, core/http/src/main/java/org/trellisldp/http/LdpResource.java, core/http/src/main/java/org/trellisldp/http/impl/RdfUtils.java, core/http/src/main/java/org/trellisldp/http/impl/TrellisDataset.java, core/http/src/test/java/org/trellisldp/http/BaseLdpResourceTest.java, core/http/src/test/java/org/trellisldp/http/LdpResourceTest.java, platform/webapp/src/main/java/org/trellisldp/webapp/TrellisApplication.java
Resolves #196 
This is a first stab at having the HTTP layer auto-initialize the backend. The triplestore impl still initializes itself independently, but that can be changed if this seems like the right approach.
=> Add backend initialization code

components/app-triplestore/src/main/java/org/trellisldp/app/triplestore/TrellisServiceBundler.java, components/app/src/test/java/org/trellisldp/app/SimpleServiceBundler.java, components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, components/triplestore/src/test/java/org/trellisldp/triplestore/ResourceServiceTest.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreSessionTest.java, core/api/src/main/java/org/trellisldp/api/RDFUtils.java, core/api/src/main/java/org/trellisldp/api/ServiceBundler.java, core/http/src/main/java/org/trellisldp/http/LdpResource.java, core/http/src/main/java/org/trellisldp/http/impl/DeleteHandler.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/main/java/org/trellisldp/http/impl/RdfUtils.java, core/http/src/main/java/org/trellisldp/http/impl/SimpleEvent.java, core/http/src/test/java/org/trellisldp/http/AbstractLdpResourceTest.java, core/http/src/test/java/org/trellisldp/http/BaseLdpResourceTest.java, core/http/src/test/java/org/trellisldp/http/LdpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/DeleteHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/HandlerBaseTest.java, core/http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/SimpleEventTest.java, platform/webapp/src/main/java/org/trellisldp/webapp/WebappServiceBundler.java
=> Move event service logic into HTTP layer

components/app/src/main/java/org/trellisldp/app/AbstractTrellisApplication.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/test/java/org/trellisldp/http/CORSAnyOriginTest.java, core/http/src/test/java/org/trellisldp/http/CORSSpecificOriginTest.java, core/http/src/test/java/org/trellisldp/http/LdpAdminResourceTest.java, core/http/src/test/java/org/trellisldp/http/LdpForbiddenResourceTest.java, core/http/src/test/java/org/trellisldp/http/LdpResourceNoAgentTest.java, core/http/src/test/java/org/trellisldp/http/LdpResourceTest.java, core/http/src/test/java/org/trellisldp/http/LdpUnauthorizedResourceTest.java, core/http/src/test/java/org/trellisldp/http/LdpUserResourceTest.java, platform/webapp/src/main/java/org/trellisldp/webapp/TrellisApplication.java, platform/webapp/src/test/java/org/trellisldp/webapp/AppUtilsTest.java
Resolves #202
The new class name is `TrellisHttpResource`
=> Rename http.LdpResource class

components/file/src/main/java/org/trellisldp/file/FileResource.java, components/test/src/main/java/org/trellisldp/test/LdpBasicContainerTests.java, components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResource.java, core/api/src/main/java/org/trellisldp/api/JoiningResourceService.java, core/api/src/main/java/org/trellisldp/api/Resource.java, core/api/src/test/java/org/trellisldp/api/JoiningResourceServiceTest.java, core/http/src/main/java/org/trellisldp/http/impl/DeleteHandler.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractLdpResourceTest.java, core/http/src/test/java/org/trellisldp/http/BaseLdpResourceTest.java
Resolves #214
I'd like to add some more tests, but this is a start.
=> Support PUT-uncontained for creation requests

components/test/src/main/java/org/trellisldp/test/ResourceServiceTests.java, components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java, core/api/src/main/java/org/trellisldp/api/JoiningResourceService.java, core/api/src/main/java/org/trellisldp/api/MutableDataService.java, core/api/src/test/java/org/trellisldp/api/JoiningResourceServiceTest.java, core/http/src/main/java/org/trellisldp/http/impl/DeleteHandler.java, core/http/src/test/java/org/trellisldp/http/BaseLdpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/DeleteHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/HandlerBaseTest.java
=> Refactor ResourceService::delete method

platform/webapp/build.gradle, platform/webapp/src/main/java/org/trellisldp/webapp/TrellisApplication.java, platform/webapp/src/main/resources/META-INF/javaconfiguration.properties
=> Add authentication modules to webapp

core/http/src/main/java/org/trellisldp/http/domain/HttpConstants.java, core/http/src/main/java/org/trellisldp/http/domain/TimemapGenerator.java, core/http/src/main/java/org/trellisldp/http/impl/MementoResource.java, core/http/src/test/java/org/trellisldp/http/impl/MementoResourceTest.java
=> Make RDF-based timemap structure more flexible

auth/basic/src/main/java/org/trellisldp/auth/basic/BasicAuthFilter.java, auth/oauth/src/main/java/org/trellisldp/auth/oauth/OAuthFilter.java
The two things going on here are:
1. Adding explicit type params for `orElseThrow`, which really we oughtn't have to, but I'm not going to spend my life arguing with compilers.
2. Making some anon classes static to avoid some GC (I know some RTEs are smart enough to do this themselves, but TRUST NO ONE.)
=> Making things very explicit for less-intelligent compilers

build.gradle, platform/linux/build.gradle, platform/linux/src/docker/Dockerfile, platform/linux/src/docker/command.sh, platform/linux/src/docker/config.yml
This adds a configuration for creating a docker container for Trellis and pushing that container to dockerhub.
=> Add docker configuration

components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java, core/api/src/main/java/org/trellisldp/api/ResourceService.java, core/api/src/test/java/org/trellisldp/api/ResourceServiceTest.java, core/api/src/test/java/org/trellisldp/api/TrellisUtilsTest.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java
=> Remove ResourceService::getContainer method

components/file/src/main/java/org/trellisldp/file/FileMementoService.java, components/file/src/test/java/org/trellisldp/file/FileMementoServiceTest.java, core/api/src/main/java/org/trellisldp/api/MementoService.java, core/api/src/main/java/org/trellisldp/api/NoopMementoService.java, core/api/src/test/java/org/trellisldp/api/NoopMementoServiceTest.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/core/TimemapGeneratorTest.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java
Addresses discussion in:
https://github.com/trellis-ldp/trellis/issues/263
https://github.com/trellis-ldp/trellis/issues/245
=> Pruning MementoService

components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, core/api/src/main/java/org/trellisldp/api/MutableDataService.java, core/api/src/test/java/org/trellisldp/api/ResourceServiceTest.java
=> Add default implementation of MutableDataService::create

components/app/src/main/java/org/trellisldp/app/AbstractTrellisApplication.java, platform/server/src/docker/config.yml
See related issue in the trellis-ext-db repository: https://github.com/trellis-ldp/trellis-ext-db/issues/9
=> Allow Dropwizard apps to use ENV properties

components/file/src/main/java/org/trellisldp/file/FileResource.java
The internal Graph field is an AutoCloseable and so, in theory,
this could leak resources and make things harder for the garbage
collector.
=> Replace an internal Graph with a Map

buildtools/src/main/resources/checkstyle/checkstyle.xml
https://github.com/trellis-ldp/trellis/issues/311
=> Allow JAX-RS wildcard imports

core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java
=> Turn down exception logging

core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java, core/http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java
This fixes the failing HTTP tests in #304
=> Update binary streaming in HTTP layer

components/file/src/main/java/org/trellisldp/file/FileBinary.java, components/file/src/main/java/org/trellisldp/file/FileBinaryService.java, components/file/src/test/java/org/trellisldp/file/FileBinaryServiceTest.java, core/api/src/main/java/org/trellisldp/api/Binary.java, core/api/src/main/java/org/trellisldp/api/BinaryService.java, core/api/src/test/java/org/trellisldp/api/BinaryServiceTest.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java, core/http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java
NOT FOR MERGING YET 
https://github.com/trellis-ldp/trellis/issues/306
=> Binaries fully streaming into the backend

components/io-jena/src/main/java/org/trellisldp/io/JenaIOService.java, components/io-jena/src/test/java/org/trellisldp/io/JenaIOServiceTest.java, components/test/src/main/java/org/trellisldp/test/LdpRdfTests.java, core/http/src/main/java/org/trellisldp/http/impl/HttpUtils.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java
Resolves #321
This only applies to JSON-LD requests with no `profile` parameter
=> Change default JSON-LD output to compact

core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/main/java/org/trellisldp/http/core/TrellisRequest.java, core/http/src/main/java/org/trellisldp/http/impl/BaseLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/HttpUtils.java, core/http/src/main/java/org/trellisldp/http/impl/MementoResource.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java, core/http/src/test/java/org/trellisldp/http/impl/DeleteHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/GetHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java
=> Move injected contexts out of TrellisRequest class

core/api/src/main/java/org/trellisldp/api/DefaultIdentifierService.java, core/api/src/main/java/org/trellisldp/api/IdentifierService.java
=> Less autoboxing

build.gradle, components/app-triplestore/build.gradle, components/app/build.gradle, components/constraint-rules/build.gradle, components/file/build.gradle, components/io-jena/build.gradle, components/rdfa/build.gradle, components/test/build.gradle, components/triplestore/build.gradle, components/webac/build.gradle, core/api/build.gradle, core/vocabulary/build.gradle
=> Explicitly exclude jena-osgi and include jena-arq

core/api/src/main/java/org/trellisldp/api/MementoService.java
Meets https://github.com/trellis-ldp/trellis/issues/346
=> Comment on MementoService::put

core/api/src/main/java/org/trellisldp/api/NoopAccessControlService.java, core/api/src/test/java/org/trellisldp/api/NoopAccessControlServiceTest.java
=> Add a no-op AccessControlService

components/webac/src/main/java/org/trellisldp/webac/WebACService.java
Add `@Alternative` annotation to distinguish `WebACService` from no-op default
=> Add @Alternative annotation 

build.gradle, core/http/build.gradle, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, platform/karaf/src/main/resources/features.xml
=> Use microprofile metrics

components/file/src/main/java/org/trellisldp/file/FileResource.java, components/test/src/main/java/org/trellisldp/test/ResourceServiceTests.java, components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResource.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceTest.java, components/webac/src/main/java/org/trellisldp/webac/WebACService.java, components/webac/src/test/java/org/trellisldp/webac/WebACServiceTest.java, components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAV.java, components/webdav/src/main/java/org/trellisldp/webdav/impl/WebDAVUtils.java, components/webdav/src/test/java/org/trellisldp/webdav/WebDAVTest.java, core/api/src/main/java/org/trellisldp/api/Resource.java, core/api/src/main/java/org/trellisldp/api/TrellisUtils.java, core/api/src/test/java/org/trellisldp/api/TrellisUtilsTest.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/main/java/org/trellisldp/http/impl/DeleteHandler.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java
=> Return quads from Resource::stream

components/test/src/main/java/org/trellisldp/test/LdpBasicContainerTests.java, components/test/src/main/java/org/trellisldp/test/ResourceServiceTests.java
=> Test for the absence of membership triples on LDP-BC

components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAV.java, core/http/src/main/java/org/trellisldp/http/impl/MementoResource.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceBaseUrlTest.java
=> Improve URI creation from baseUrl

components/app/src/main/java/org/trellisldp/app/AbstractTrellisApplication.java, components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAVAuthzFilter.java, components/webdav/src/test/java/org/trellisldp/webdav/TrellisWebDAVAuthzFilterTest.java, core/http/src/main/java/org/trellisldp/http/WebAcFilter.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceUnauthorizedTest.java, core/http/src/test/java/org/trellisldp/http/WebAcFilterTest.java, platform/webapp/src/main/java/org/trellisldp/webapp/TrellisApplication.java
Resolves #382
@ajs6f note that the signature for WebAcFilter (and webdav authZ filter) changes and may require adjustment to the downstream T-C* implementation.
=> Add a baseUrl parameter to the WebAcFilter class

buildtools/src/main/resources/checkstyle/checkstyle.xml
https://github.com/trellis-ldp/trellis/issues/389
=> Relax Checkstyle config for braces and wildcard imports

components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAV.java, components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAVRequestFilter.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java
https://github.com/trellis-ldp/trellis-cassandra/pull/65
https://github.com/gregjan/trellis-cassandra/pull/1
=> Adding no-arg ctors to satisfy CDI

components/test/src/main/java/org/trellisldp/test/MementoBinaryTests.java, components/test/src/main/java/org/trellisldp/test/MementoResourceTests.java, core/http/src/main/java/org/trellisldp/http/core/TimemapGenerator.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/MementoResource.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/GetHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/MementoResourceTest.java
=> Limit the memento headers to first, last, prev, next, timemap, timegate

core/api/src/main/java/org/trellisldp/api/Metadata.java, core/api/src/test/java/org/trellisldp/api/MetadataTest.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java
https://github.com/trellis-ldp/trellis/issues/410
=> Added new hasAcl slot to Metadata

core/http/src/main/java/org/trellisldp/http/WebAcFilter.java, core/http/src/test/java/org/trellisldp/http/WebAcFilterTest.java
=> Restrict audit stream to users with acl:Control

core/http/src/main/java/org/trellisldp/http/core/HttpConstants.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/HttpUtils.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java
Resolves #420
This removes the half-baked TPF feature from the core of Trellis.
=> Remove TPF support

components/webac/src/main/java/org/trellisldp/webac/WebACService.java, core/http/src/main/java/org/trellisldp/http/AgentAuthorizationFilter.java, core/http/src/main/java/org/trellisldp/http/WebAcFilter.java
These fixes, plus some adjustments on the trellis-cassandra side, have resulted in a working repository with basic auth and webac.
=> Added no-arg constructors to support CDI proxies.

core/http/src/main/java/org/trellisldp/http/core/TrellisRequest.java
These should have been removed as part of the #421 PR
=> Remove unused query params

build.gradle
=> Update to Jena 3.12

core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/OptionsHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java
=> Accept-Post should include the wildcard type

components/webac/src/main/java/org/trellisldp/webac/WebAcService.java, core/api/src/main/java/org/trellisldp/api/NoopResourceService.java, core/api/src/test/java/org/trellisldp/api/NoopResourceServiceTest.java
=> Add a no-op resource service implementation

core/api/src/main/java/org/trellisldp/api/NoopAuditService.java, core/api/src/main/java/org/trellisldp/api/NoopEventService.java, core/api/src/main/java/org/trellisldp/api/NoopImplementation.java, core/api/src/main/java/org/trellisldp/api/NoopMementoService.java, core/api/src/main/java/org/trellisldp/api/NoopNamespaceService.java, core/api/src/main/java/org/trellisldp/api/NoopResourceService.java
https://github.com/trellis-ldp/trellis/issues/446
=> Use CDI stereotype for concision

core/api/src/main/java/org/trellisldp/api/DefaultIdentifierService.java
=> Remove Alternative annotation on DefaultIdentifierService

components/app-triplestore/src/main/java/org/trellisldp/app/triplestore/TrellisServiceBundler.java, components/app/src/test/java/org/trellisldp/app/SimpleServiceBundler.java, components/webdav/src/test/java/org/trellisldp/webdav/AbstractWebDAVTest.java, components/webdav/src/test/java/org/trellisldp/webdav/TrellisWebDAVRequestFilterTest.java, core/http/src/main/java/org/trellisldp/http/core/DefaultEtagGenerator.java, core/http/src/main/java/org/trellisldp/http/core/DefaultTimemapGenerator.java, core/http/src/main/java/org/trellisldp/http/core/EtagGenerator.java, core/http/src/main/java/org/trellisldp/http/core/TimemapGenerator.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/core/TimemapGeneratorTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java, core/http/src/test/java/org/trellisldp/http/impl/GetHandlerTest.java, platform/osgi/src/main/java/org/trellisldp/osgi/TrellisServiceBundler.java, platform/webapp/src/main/java/org/trellisldp/webapp/WebappServiceBundler.java
=> Add default implementations for http.core interfaces

core/http/src/main/java/org/trellisldp/http/core/DefaultTimemapGenerator.java, core/http/src/main/java/org/trellisldp/http/core/TimemapGenerator.java, core/http/src/test/java/org/trellisldp/http/core/DefaultTimemapGeneratorTest.java
=> Simplify TimemapGenerator interface

components/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, components/webac/src/test/java/org/trellisldp/webac/WebAcFilterTest.java
=> Do not produce an ACL link header in a DELETE response

components/test/src/main/java/org/trellisldp/test/InMemoryBinaryService.java, components/test/src/main/java/org/trellisldp/test/InMemoryResourceService.java, components/test/src/test/java/org/trellisldp/test/InMemoryBinaryServiceTest.java, components/test/src/test/java/org/trellisldp/test/InMemoryResourceServiceTest.java
https://github.com/trellis-ldp/trellis/issues/440
First draft, needs tests
NOT YET FOR MERGING
=> Introducing in-memory services

core/http/build.gradle, core/http/src/main/java/org/trellisldp/http/impl/HttpUtils.java
Resolves #474
Note: this adds a dependency on commons-lang3 to the HTTP layer
=> Better header parameter parsing

components/webac/src/main/java/org/trellisldp/webac/WebAcService.java
Resolves #478
This makes a method that is currently private into a public static method for easier re-use.
=> Make getCacheKey public

components/agent/src/main/java/org/trellisldp/agent/DefaultAgentService.java, components/audit/src/main/java/org/trellisldp/audit/DefaultAuditService.java, components/constraint-rules/src/main/java/org/trellisldp/constraint/LdpConstraintService.java, components/event-serialization/src/main/java/org/trellisldp/event/DefaultActivityStreamService.java, components/io-jena/src/main/java/org/trellisldp/io/JenaIOService.java, components/rdfa/src/main/java/org/trellisldp/rdfa/DefaultRdfaWriterService.java, core/api/src/main/java/org/trellisldp/api/DefaultIdentifierService.java
=> Add ApplicationScoped annotations

components/app/build.gradle
The JPMS build is currently failing. This adjustment fixes the errors.
=> Fix JPMS-based build

components/webac/src/main/java/org/trellisldp/webac/Authorization.java, components/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, components/webac/src/main/java/org/trellisldp/webac/WebAcService.java, components/webac/src/test/java/org/trellisldp/webac/AuthorizationTest.java, components/webac/src/test/java/org/trellisldp/webac/WebAcFilterTest.java, components/webac/src/test/java/org/trellisldp/webac/WebAcServiceTest.java
Resolves #490
(Most of this is just adjusting test code because the method signature changed)
=> Remove support for acl:origin

build.gradle, platform/bom/build.gradle, settings.gradle
Resolves #501
There's no java code here, just gradle.
=> Add support for BOM generation

build.gradle, platform/karaf/src/main/resources/features.xml, platform/osgi/src/test/java/org/trellisldp/osgi/OSGiTest.java
=> Adjust OSGi tests/provisioning

build.gradle, notifications/reactive/bnd.bnd, notifications/reactive/build.gradle, notifications/reactive/src/main/java/module-info.java, notifications/reactive/src/main/java/org/trellisldp/reactive/ReactiveEventService.java, notifications/reactive/src/main/java/org/trellisldp/reactive/package-info.java, notifications/reactive/src/main/resources/META-INF/beans.xml, notifications/reactive/src/test/java/org/trellisldp/reactive/ReactiveEventServiceTest.java, notifications/reactive/src/test/java/org/trellisldp/reactive/TestCollector.java, notifications/reactive/src/test/resources/logback-test.xml, settings.gradle
Resolves #483
This is still a bit experimental, but it passes the tests and there is so little code here, that I am inclined to move this forward.
=> Implement microprofile reactive messaging

components/constraint-rules/src/test/java/org/trellisldp/constraint/LdpConstraintServiceTest.java, components/dropwizard/src/test/java/org/trellisldp/dropwizard/NoInitTrellisApplicationTest.java, components/test/src/main/java/org/trellisldp/test/MementoTimeGateTests.java, components/test/src/main/java/org/trellisldp/test/MementoTimeMapTests.java, components/test/src/main/java/org/trellisldp/test/ResourceServiceTests.java
Some minor changes here, tightening up parts of the testing code.
=> Minor code clean-up

components/app/build.gradle, components/app/src/main/java/org/trellisldp/app/AppUtils.java, components/app/src/test/java/org/trellisldp/app/AppUtilsTest.java, platform/app-mp-triplestore/src/main/java/org/trellisldp/app/mp/triplestore/WebApplication.java
This moves the printBanner method into a layer where it can be more
easily reused.
=> Create utility class in trellis-app

build.gradle, platform/bom/build.gradle, platform/quarkus/build.gradle, platform/quarkus/src/main/java/org/trellisldp/quarkus/AuthorizationCache.java, platform/quarkus/src/main/java/org/trellisldp/quarkus/CDIConstraintServices.java, platform/quarkus/src/main/java/org/trellisldp/quarkus/ProfileCache.java, platform/quarkus/src/main/java/org/trellisldp/quarkus/ServiceProviders.java, platform/quarkus/src/main/java/org/trellisldp/quarkus/TrellisApplication.java, platform/quarkus/src/main/java/org/trellisldp/quarkus/TrellisCache.java, platform/quarkus/src/main/java/org/trellisldp/quarkus/package-info.java, platform/quarkus/src/main/resources/META-INF/beans.xml, platform/quarkus/src/test/java/org/trellisldp/quarkus/ApplicationTest.java, platform/quarkus/src/test/resources/namespaces.json, settings.gradle
This adds a quarkus/microprofile project to trellis
Related to #470
=> Add quarkus-based project

build.gradle, core/http/build.gradle, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java
Resolves #530
This adds some basic OpenAPI annotations to the main JAX-RS resource.
=> Add OpenAPI annotations

platform/quarkus/build.gradle
The quarkus component is importing an old javax.activation jar, and the version is incorrect.
=> Fix incorrect import

core/api/src/main/java/org/trellisldp/api/Event.java, core/api/src/main/java/org/trellisldp/api/NoopEventSerializationService.java, core/api/src/test/java/org/trellisldp/api/NoopEventSerializationServiceTest.java, core/http/src/main/java/org/trellisldp/http/core/SimpleEvent.java, core/http/src/test/java/org/trellisldp/http/core/SimpleEventTest.java, core/http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java, notifications/amqp/src/test/java/org/trellisldp/amqp/AmqpEventServiceTest.java, notifications/event-jackson/src/main/java/org/trellisldp/event/jackson/ActivityStreamMessage.java, notifications/event-jackson/src/test/java/org/trellisldp/event/jackson/DefaultEventSerializationServiceTest.java, notifications/event-jsonb/src/main/java/org/trellisldp/event/jsonb/ActivityStreamMessage.java, notifications/event-jsonb/src/test/java/org/trellisldp/event/jsonb/DefaultEventSerializationServiceTest.java, notifications/jms/src/test/java/org/trellisldp/jms/JmsEventServiceTest.java, notifications/kafka/src/main/java/org/trellisldp/kafka/KafkaEventService.java, notifications/kafka/src/test/java/org/trellisldp/kafka/KafkaEventServiceTest.java, notifications/reactive/src/test/java/org/trellisldp/reactive/ReactiveEventServiceTest.java
=> Change ::getTarget to ::getObject in Event interface

components/cdi/bnd.bnd, components/cdi/build.gradle, components/cdi/src/main/java/module-info.java, components/cdi/src/main/java/org/trellisldp/cdi/CDIConstraintServices.java, components/cdi/src/main/java/org/trellisldp/cdi/package-info.java, components/cdi/src/main/resources/META-INF/beans.xml, components/cdi/src/test/java/org/trellisldp/cdi/CDIConstraintServicesTest.java, components/cdi/src/test/resources/logback-test.xml, platform/bom/build.gradle, platform/openliberty/build.gradle, platform/quarkus/build.gradle, settings.gradle
Resolves #544
This adds a CDI component and integrates it into the two
microprofile-based platforms.
=> Add CDI component

.travis.yml, build.gradle, buildtools/src/main/resources/pmd/pmd.xml, components/app-triplestore/build.gradle, gradle/wrapper/gradle-wrapper.properties, gradlew
This won't fail builds, based on spotbugs/pmd rule violations, but it will report them to the console. We can decide separately how to address these warnings.
=> Add spotbugs, pmd plugins

components/app/src/main/java/org/trellisldp/app/AppUtils.java, components/webac/src/main/java/org/trellisldp/webac/WebAcService.java, platform/openliberty/src/main/java/org/trellisldp/openliberty/WebApplication.java, platform/quarkus/src/main/java/org/trellisldp/quarkus/TrellisApplication.java
Resolves #561
See the [`@PostConstruct` documentation](https://docs.oracle.com/javaee/7/api/javax/annotation/PostConstruct.html) for more details
=> Remove exceptions from PostConstruct methods

components/io-jena/src/main/java/org/trellisldp/io/JenaIOService.java, components/io-jena/src/test/java/org/trellisldp/io/JenaIOServiceTest.java
=> Do not register relative, local namespaces

components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAV.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpFilter.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/main/java/org/trellisldp/http/core/TrellisExtensions.java, core/http/src/main/java/org/trellisldp/http/impl/HttpUtils.java, core/http/src/test/java/org/trellisldp/http/core/TrellisExtensionsTest.java, core/http/src/test/java/org/trellisldp/http/impl/HttpUtilsTest.java
Related to #535
This PR applies some of the existing work on defining an extension pattern to the HTTP filter and to the webdav module
=> Improve support for named graph extension mechanism

components/dropwizard/src/main/java/org/trellisldp/dropwizard/config/CORSConfiguration.java, platform/quarkus/src/main/resources/application.properties
This adds the `WWW-Authenticate` header to the various CORS configurations
=> Add www-authenticate header to default cors configuration

core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/MementoResource.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/GetHandlerTest.java
=> Consolidate Vary header creation

.travis.yml, build.gradle, components/cache/build.gradle, platform/karaf/src/main/resources/features.xml, platform/osgi/build.gradle, platform/osgi/src/test/java/org/trellisldp/osgi/OSGiTest.java
This just expands the OSGi provisioning support a bit to some additional components. It also adds a build task to test OSGi provisioning in the CI environment.
=> Add OSGi provisioning support for some more trellis components

core/api/src/main/java/org/trellisldp/api/Metadata.java, core/api/src/test/java/org/trellisldp/api/MetadataTest.java
=> Include binary metadata when building from a Resource

build.gradle, platform/quarkus/build.gradle, settings.gradle
Now that Quarkus has released 1.0, this updates Trellis to that version.
=> Upgrade to quarkus 1.0

components/constraint-rules/src/main/java/org/trellisldp/constraint/LdpConstraintService.java
=> More description for constraint failures

build.gradle, gradle.properties
This just separates configuration from version management.
=> Move version management into gradle.properties

components/dropwizard/src/main/java/org/trellisldp/dropwizard/AbstractTrellisApplication.java, components/dropwizard/src/main/java/org/trellisldp/dropwizard/TrellisUtils.java, components/dropwizard/src/test/java/org/trellisldp/dropwizard/TrellisUtilsTest.java, components/webac/build.gradle, components/webac/src/main/java/org/trellisldp/webac/WebAcService.java, components/webac/src/main/resources/org/trellisldp/webac/defaultAcl.ttl, components/webac/src/test/java/org/trellisldp/webac/WebAcServiceTest.java
This reverts commit dd6de5d817fbc7b38f36399052ec1dc51fed015f.
The implementation was flawed and needs to be reverted
=> Revert "Allow custom ACL definitions"

components/dropwizard/src/test/java/org/trellisldp/dropwizard/AnyOriginTest.java, components/dropwizard/src/test/java/org/trellisldp/dropwizard/NoInitTrellisApplicationTest.java, components/dropwizard/src/test/java/org/trellisldp/dropwizard/SpecificOriginTest.java, components/dropwizard/src/test/java/org/trellisldp/dropwizard/TrellisApplicationTest.java, gradle.properties
=> Update dropwizard to 2.0

core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceTest.java
=> Return CompletionStage in HTTP interface

components/app/src/test/java/org/trellisldp/app/CDIServiceBundlerTest.java, components/file/src/main/java/org/trellisldp/file/FileMementoService.java, platform/openliberty/src/main/java/org/trellisldp/openliberty/TrellisServiceSupplier.java, platform/quarkus/src/main/java/org/trellisldp/quarkus/ServiceProviders.java
=> Update CDI annotations for memento service

components/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, components/webac/src/test/java/org/trellisldp/webac/WebAcFilterTest.java, components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAVRequestFilter.java, core/api/src/main/java/org/trellisldp/api/TrellisUtils.java, core/api/src/test/java/org/trellisldp/api/TrellisUtilsTest.java
=> Ensure that path parameters with leading slashes are normalized

core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java, core/http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java
=> Fix duplicate slash on root resource

.github/workflows/build_deploy.yml, .github/workflows/gradle.yml, .github/workflows/pull_requests.yml, .travis.yml, buildtools/src/main/resources/docker/publishToGitHub.sh
=> Add GH action configuration

.github/workflows/build_deploy.yml, .github/workflows/pull_requests.yml, .github/workflows/release.yml, buildtools/src/main/resources/docker/publishToGitHub.sh
This is mostly a test related to how docker versions are pushed to the github package repository
=> Adjust gh package rules

core/http/src/main/java/org/trellisldp/http/impl/BaseLdpHandler.java, core/http/src/test/java/org/trellisldp/http/impl/GetHandlerTest.java
=> Changed the hash algorithm from MD5 to SHA256

build.gradle
=> Use provided scope for JavaEE dependencies

components/webac/build.gradle, components/webac/src/main/java/org/trellisldp/webac/WebAcService.java, components/webac/src/main/resources/org/trellisldp/webac/defaultAcl.ttl, components/webac/src/test/java/org/trellisldp/webac/WebAcServiceTest.java, components/webac/src/test/resources/badTurtle.ttl, components/webac/src/test/resources/customAcl.ttl
=> Make it possible to customize the default ACL

core/http/src/main/java/org/trellisldp/http/core/Forwarded.java, core/http/src/main/java/org/trellisldp/http/core/TrellisRequest.java, core/http/src/test/java/org/trellisldp/http/core/ForwardedTest.java, core/http/src/test/java/org/trellisldp/http/core/TrellisRequestTest.java
=> Add support for X-Forwarded-* and Forwarded headers

components/io-jena/src/main/java/org/trellisldp/io/JenaIOService.java, components/io-jena/src/test/java/org/trellisldp/io/JenaIOServiceTest.java, core/vocabulary/src/main/java/org/trellisldp/vocabulary/JSONLD.java, core/vocabulary/src/main/java/org/trellisldp/vocabulary/RDF.java, core/vocabulary/src/test/java/org/trellisldp/vocabulary/JSONLDTest.java
=> Add JSON-LD 1.1 IRIs to the RDF vocabulary

auth/basic/build.gradle, auth/jwt/build.gradle, auth/oauth/build.gradle, build.gradle, components/app/build.gradle, components/audit/build.gradle, components/cache/build.gradle, components/cdi/build.gradle, components/constraint-rules/build.gradle, components/file/build.gradle, components/io-jena/build.gradle, components/rdfa/build.gradle, components/webac/build.gradle, components/webdav/build.gradle, core/api/build.gradle, gradle.properties, notifications/amqp/build.gradle, notifications/event-jackson/build.gradle, notifications/event-jsonb/build.gradle, notifications/jms/build.gradle, notifications/kafka/build.gradle
Resolves #616
Mutation tests can be run with `./gradlew pitest`
=> Add plugin for mutation testing

components/io-jena/src/main/java/org/trellisldp/io/JenaIOService.java, components/io-jena/src/test/java/org/trellisldp/io/JenaIOServiceTest.java, core/vocabulary/src/main/java/org/trellisldp/vocabulary/Trellis.java
=> Support per-request relative IRI configuration

auth/oauth/src/main/java/module-info.java, auth/oauth/src/main/java/org/trellisldp/auth/oauth/FederatedJwtAuthenticator.java, auth/oauth/src/main/java/org/trellisldp/auth/oauth/JwksAuthenticator.java, auth/oauth/src/main/java/org/trellisldp/auth/oauth/JwtAuthenticator.java, build.gradle
The jjwt dependency now works with Java11 modules.
=> Update jjwt to 0.11

components/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, components/webac/src/test/java/org/trellisldp/webac/WebAcFilterTest.java, core/http/src/main/java/org/trellisldp/http/core/TrellisRequest.java
=> Add support for in-domain WebIDs

components/webac/src/main/java/org/trellisldp/webac/WebAcService.java, components/webac/src/test/java/org/trellisldp/webac/WebAcServiceTest.java
=> Support disconnected hierarchies with WebAC

platform/dropwizard/src/main/java/org/trellisldp/app/triplestore/AppUtils.java
=> Use a package whitelist for ActiveMQ connections

platform/server/build.gradle, platform/server/src/deb/postInstall.sh, platform/server/src/deb/preInstall.sh, platform/server/src/deb/preUninstall.sh, platform/server/src/rpm/postInstall.sh, platform/server/src/rpm/preInstall.sh, platform/server/src/rpm/preUninstall.sh, settings.gradle
=> Remove ospackage plugin

.travis.yml, buildtools/src/main/resources/docker/publishToDockerHub.sh, platform/dropwizard/build.gradle, settings.gradle
=> Remove use of docker plugin

components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResource.java, components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceTest.java
This makes it possible to apply the resource metadata extension to the Triplestore implementation.
=> Better support for resource metadata extensions

core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java
=> Fix duplicate slashes on PUT requests to root resource

components/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, components/webac/src/test/java/org/trellisldp/webac/WebAcFilterTest.java
=> Include acl link headers in responses to ACL resources

core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java
=> Better content negotiation for extension resources

components/test/src/main/java/org/trellisldp/test/AbstractApplicationAuthTests.java, components/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, components/webac/src/test/java/org/trellisldp/webac/WebAcFilterTest.java
=> Use relative links for ACL link headers

.github/workflows/build_deploy.yml, .github/workflows/pull_requests.yml
=> Add gradle wrapper validation to CI

components/constraint-rules/src/main/java/org/trellisldp/constraint/LdpConstraintService.java, components/constraint-rules/src/test/java/org/trellisldp/constraint/LdpConstraintServiceTest.java, core/api/src/main/java/org/trellisldp/api/ConstraintService.java, core/api/src/test/java/org/trellisldp/api/ConstraintServiceTest.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java
=> Add resource identifer to ConstraintService::constrainedBy

components/dropwizard/src/test/java/org/trellisldp/dropwizard/TrellisUtilsTest.java, components/file/src/main/java/org/trellisldp/file/FileResource.java, components/file/src/test/java/org/trellisldp/file/FileResourceTest.java, components/test/src/main/java/org/trellisldp/test/ResourceServiceTests.java, components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResource.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceTest.java, components/webac/src/main/java/org/trellisldp/webac/WebAcService.java, components/webac/src/test/java/org/trellisldp/webac/WebAcServiceTest.java, components/webdav/src/main/java/org/trellisldp/webdav/impl/WebDAVUtils.java, components/webdav/src/test/java/org/trellisldp/webdav/AbstractWebDAVTest.java, core/api/src/main/java/org/trellisldp/api/Metadata.java, core/api/src/main/java/org/trellisldp/api/Resource.java, core/api/src/test/java/org/trellisldp/api/MetadataTest.java, core/api/src/test/java/org/trellisldp/api/ResourceTest.java, core/http/src/main/java/org/trellisldp/http/impl/HttpUtils.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java
=> Generalize Resource::hasAcl method

components/test/build.gradle, components/test/src/main/java/org/trellisldp/test/AbstractApplicationAuditTests.java, components/test/src/main/java/org/trellisldp/test/AbstractApplicationAuthTests.java, components/test/src/main/java/org/trellisldp/test/AbstractApplicationEventTests.java, components/test/src/main/java/org/trellisldp/test/AbstractApplicationLdpTests.java, components/test/src/main/java/org/trellisldp/test/AbstractApplicationMementoTests.java, components/test/src/main/java/org/trellisldp/test/AbstractResourceServiceTests.java, components/test/src/main/java/org/trellisldp/test/AuditTests.java, components/test/src/main/java/org/trellisldp/test/AuthAdministratorTests.java, components/test/src/main/java/org/trellisldp/test/AuthAnonymousTests.java, components/test/src/main/java/org/trellisldp/test/AuthOtherUserTests.java, components/test/src/main/java/org/trellisldp/test/AuthUserTests.java, components/test/src/main/java/org/trellisldp/test/EventTests.java, components/test/src/main/java/org/trellisldp/test/LdpBasicContainerTests.java, components/test/src/main/java/org/trellisldp/test/LdpBinaryTests.java, components/test/src/main/java/org/trellisldp/test/LdpDirectContainerTests.java, components/test/src/main/java/org/trellisldp/test/LdpIndirectContainerTests.java, components/test/src/main/java/org/trellisldp/test/LdpRdfTests.java, components/test/src/main/java/org/trellisldp/test/MementoBinaryTests.java, components/test/src/main/java/org/trellisldp/test/MementoCommonTests.java, components/test/src/main/java/org/trellisldp/test/MementoResourceTests.java, components/test/src/main/java/org/trellisldp/test/MementoTimeGateTests.java, components/test/src/main/java/org/trellisldp/test/MementoTimeMapTests.java, components/test/src/main/java/org/trellisldp/test/ResourceServiceTests.java, platform/quarkus/build.gradle, platform/quarkus/src/test/java/org/trellisldp/quarkus/LdpTest.java, platform/quarkus/src/test/java/org/trellisldp/quarkus/MementoTest.java
=> Rework integration test structure

build.gradle, components/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, components/webac/src/test/java/org/trellisldp/webac/WebAcFilterTest.java
=> Verify read controls with PATCH

core/api/src/main/java/org/trellisldp/api/TrellisUtils.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java
Add more debug logging
Related to #783
=> Improve deprecation documentation

core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java
This sets a content-type for the responses that result in constraint violations.
=> Improve error responses for constraint violations

platform/quarkus/build.gradle
...rather than `enforcedPlatform`
=> Use platform for quarkus

core/http/src/main/java/org/trellisldp/http/core/HttpConstants.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java
=> Add configuration to enable/disable LDP model changes

components/webac/src/main/java/org/trellisldp/webac/WebAcService.java, components/webac/src/test/java/org/trellisldp/webac/WebAcServiceTest.java
=> Support externalized default root ACL resources

build.gradle
This adds support for the `./gradlew downloadLicenses` task
=> Add license download configuration

components/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, components/webac/src/test/java/org/trellisldp/webac/WebAcFilterTest.java
=> Allow WebAC checks to be disabled at runtime via a configuration

.github/workflows/cd-config.yml, .travis.yml, platform/dropwizard/src/main/docker/Dockerfile.jvm, platform/quarkus/src/main/docker/Dockerfile.jvm
=> Use Java 11 for Docker images

components/file/src/test/java/org/trellisldp/file/FileBinaryServiceTest.java, components/file/src/test/java/org/trellisldp/file/FileNamespaceServiceTest.java, components/file/src/test/java/org/trellisldp/file/FileUtilsTest.java, components/io-jena/src/test/java/org/trellisldp/io/JenaIOServiceTest.java, components/jdbc/src/test/java/org/trellisldp/jdbc/DBResourceTest.java, components/namespaces/src/test/java/org/trellisldp/namespaces/SimpleNamespaceServiceTest.java, components/rdfa/src/test/java/org/trellisldp/rdfa/DefaultRdfaWriterServiceTest.java, core/http/src/test/java/org/trellisldp/http/impl/DeleteHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/GetHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/HttpUtilsTest.java, core/http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PostHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PutHandlerTest.java
This cleans up some Sonar warnings about the test code
=> Test code clean-up

components/test/src/main/java/org/trellisldp/test/MementoBinaryTests.java, components/test/src/main/java/org/trellisldp/test/MementoResourceTests.java
=> Remove flaky memento test

core/vocabulary/src/main/java/org/trellisldp/vocabulary/Trellis.java, core/vocabulary/src/test/java/org/trellisldp/vocabulary/TrellisTest.java
=> Add effectiveAcl vocabulary term

components/dropwizard/src/main/java/org/trellisldp/dropwizard/TrellisUtils.java, components/webac/src/main/java/org/trellisldp/webac/AuthorizedModes.java, components/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, components/webac/src/main/java/org/trellisldp/webac/WebAcService.java, components/webac/src/test/java/org/trellisldp/webac/WebAcFilterTest.java, components/webac/src/test/java/org/trellisldp/webac/WebAcServiceTest.java, platform/quarkus/src/main/java/org/trellisldp/quarkus/AuthorizationCache.java
=> Return effective ACL in WAC service

azure-pipelines.yml
This updates the Azure pipeline to use Java 11
=> Use Java 11 for azure pipeline

platform/dropwizard/src/main/docker/Dockerfile.jvm, platform/quarkus/src/main/docker/Dockerfile.jvm
=> Use 11-jre-slim openjdk docker base image

README.md, buildtools/src/main/resources/docker/publishToDockerHub.sh, buildtools/src/main/resources/docker/publishToGitHub.sh
=> Change container name to trellis-postgresql

platform/openliberty/src/main/liberty/config/server.xml
Update the open liberty feature to MicroProfile 3.3
=> Update openliberty to MP 3.3

components/jena/src/main/java/org/trellisldp/jena/JenaIOService.java, platform/quarkus/src/main/resources/application.properties
=> Adjust jena configuration keys

build.gradle, platform/osgi/build.gradle, platform/osgi/src/test/java/org/trellisldp/osgi/OSGiTest.java
This updates the OSGi dependencies to their latest versions
=> Update OSGi dependencies

buildtools/src/main/resources/docker/publishToGitHub.sh
=> Publish trellis docker image to GH packages

components/file/src/main/java/org/trellisldp/file/FileNamespaceService.java, components/file/src/test/java/org/trellisldp/file/FileNamespaceServiceTest.java
This checks some additional conditions in the `trellis-file` component
=> Additional unit tests

components/rdfa/src/main/java/module-info.java, components/rdfa/src/main/java/org/trellisldp/rdfa/DefaultRdfaWriterService.java, components/rdfa/src/test/java/org/trellisldp/rdfa/DefaultRdfaWriterServiceTest.java
=> Improve how RDFa service loads template resources

auth/oauth/src/main/java/org/trellisldp/oauth/OAuthFilter.java, components/file/src/test/java/org/trellisldp/file/FileBinaryServiceTest.java, components/file/src/test/java/org/trellisldp/file/FileNamespaceServiceTest.java, components/jena/src/test/java/org/trellisldp/jena/JenaIOServiceTest.java, components/rdfa/src/test/java/org/trellisldp/rdfa/DefaultRdfaWriterServiceTest.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java, components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceTest.java, components/webdav/src/test/java/org/trellisldp/webdav/WebDAVNoBaseUrlTest.java, core/api/src/main/java/org/trellisldp/api/Syntax.java, core/api/src/test/java/org/trellisldp/api/ResourceServiceTest.java, notifications/event-jackson/src/test/java/org/trellisldp/event/jackson/DefaultEventSerializationServiceTest.java, notifications/event-jsonb/src/main/java/org/trellisldp/event/jsonb/DefaultEventSerializationService.java
This makes the visibility of private static functions more consistent across the codebase
=> Simplify static method visibility

.github/workflows/ci-config.yml, .travis.yml
=> Publish snapshots to Sonatype

.github/workflows/ci-config.yml, .travis.yml, build.gradle
=> Move sonar analysis to GH Action

.github/workflows/cd-config.yml, .github/workflows/ci-config.yml, .travis.yml
=> Move docker publication to GH Action

.github/workflows/cd-config.yml
This adds sonar analysis to release tags, and builds only on Java 11
=> Adjust CD configuration

.github/workflows/cd-config.yml, .github/workflows/ci-config.yml
This moves deployment-related workflows into `cd-config`
=> Reorganize GH action workflows

.github/workflows/cd-config.yml, .github/workflows/ci-config.yml, .travis.yml, README.md, build.gradle, platform/dropwizard/build.gradle
The SonarCloud integration works much better with Travis-CI
=> Use Travis-CI for SonarCloud integration

.github/workflows/ci-config.yml
=> Add Java 14 check to CI

auth/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java
Related to #893
This is a minor adjustment to how the trailing slash is generated for `effectiveAcl` resources.
=> Adjust trailing slash generation for inherited effective ACLs

core/api/src/main/java/org/trellisldp/api/StorageConflictException.java, core/api/src/test/java/org/trellisldp/api/StorageConflictExceptionTest.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java
=> Add storage conflict exception class

components/dropwizard/src/main/java/org/trellisldp/dropwizard/AbstractTrellisApplication.java, components/dropwizard/src/test/java/org/trellisldp/dropwizard/SimpleNoInitTrellisApp.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java
=> Rework exception handling in HTTP layer

core/api/src/test/java/org/trellisldp/api/ResourceTest.java, core/api/src/test/java/org/trellisldp/api/SyntaxTest.java
Some minor test code clean-up, as reported by Sonar
=> Clean up test code

platform/dropwizard/src/main/docker/Dockerfile.jvm, platform/quarkus/src/main/docker/Dockerfile.jvm
=> Disallow remote JSON-LD contexts

components/jdbc/src/main/java/org/trellisldp/jdbc/DBResourceService.java, components/jdbc/src/main/java/org/trellisldp/jdbc/DBUtils.java, components/jdbc/src/test/java/org/trellisldp/jdbc/DBResourceTest.java, components/jdbc/src/test/java/org/trellisldp/jdbc/DBUtilsTest.java
=> Constrain deletes on containers

core/api/src/test/java/org/trellisldp/api/SyntaxTest.java
This tests a previously-missed condition
=> Additional testing

core/api/src/main/java/org/trellisldp/api/TrellisUtils.java, core/api/src/test/java/org/trellisldp/api/SyntaxTest.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/main/java/org/trellisldp/http/impl/BaseLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/HttpUtils.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java
=> Support URLs with spaces

auth/webac/src/main/java/org/trellisldp/webac/WebAcService.java
=> Additional debug logging for ACL lookups

auth/basic/build.gradle, auth/jwt/build.gradle, auth/oauth/build.gradle, auth/webac/build.gradle, build.gradle, components/app/build.gradle, components/audit/build.gradle, components/cache/build.gradle, components/cdi/build.gradle, components/constraint/build.gradle, components/file/build.gradle, components/jena/build.gradle, components/rdfa/build.gradle, components/webdav/build.gradle, core/api/build.gradle, core/http/build.gradle, notifications/amqp/build.gradle, notifications/event-jackson/build.gradle, notifications/event-jsonb/build.gradle, notifications/jms/build.gradle, notifications/kafka/build.gradle, platform/karaf/src/main/resources/features.xml, settings.gradle
This primarily updates the PITest plugin
=> Plugin and tool updates

auth/webac/src/main/java/org/trellisldp/webac/WebAcService.java, auth/webac/src/test/java/org/trellisldp/webac/WebAcServiceTest.java
=> Add WebAC initialization configuration

auth/jwt/src/main/java/org/trellisldp/jwt/WebIdSecurityContext.java, components/dropwizard/src/main/java/org/trellisldp/dropwizard/config/JsonLdConfiguration.java, components/dropwizard/src/test/java/org/trellisldp/dropwizard/config/TrellisConfigurationTest.java, components/dropwizard/src/test/resources/config1.yml, components/dropwizard/src/test/resources/trellis-config.yml, components/jena/src/main/java/org/trellisldp/jena/JenaIOService.java, platform/dropwizard/src/main/dist/etc/config.yml, platform/dropwizard/src/main/java/org/trellisldp/dropwizard/app/TrellisServiceBundler.java, platform/dropwizard/src/test/java/org/trellisldp/dropwizard/app/TrellisConfigurationTest.java, platform/dropwizard/src/test/resources/config1.yml, platform/dropwizard/src/test/resources/trellis-config.yml
=> Improve terminology for accept lists

components/dropwizard/README.md, platform/dropwizard/README.md
=> Update dropwizard docs with new terminology

.github/workflows/cd-config.yml
This simplifies the CD pipeline a bit
=> Adjust CD pipeline configuration

components/file/src/main/java/org/trellisldp/file/FileBinaryService.java, components/file/src/test/java/org/trellisldp/file/FileBinaryServiceTest.java, components/test/src/main/java/org/trellisldp/test/InMemoryBinaryService.java, components/test/src/test/java/org/trellisldp/test/InMemoryBinaryServiceTest.java, components/webdav/src/test/java/org/trellisldp/webdav/AbstractWebDAVTest.java, core/api/src/main/java/org/trellisldp/api/BinaryService.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java
=> Add hint to binary service identifier service

auth/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, auth/webac/src/test/java/org/trellisldp/webac/WebAcFilterTest.java, components/dropwizard/src/main/java/org/trellisldp/dropwizard/AbstractTrellisApplication.java, components/test/src/main/java/org/trellisldp/test/ResourceServiceTests.java, components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAVRequestFilter.java, components/webdav/src/test/java/org/trellisldp/webdav/AbstractWebDAVTest.java, components/webdav/src/test/java/org/trellisldp/webdav/TrellisWebDAVRequestFilterTest.java, core/api/src/main/java/org/trellisldp/api/ResourceService.java, core/api/src/test/java/org/trellisldp/api/ResourceServiceTest.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/main/java/org/trellisldp/http/impl/BaseLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java
=> Support partitionability in resource service

auth/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, components/dropwizard/src/main/java/org/trellisldp/dropwizard/CrossOriginResourceSharingFilter.java, components/test/src/main/java/org/trellisldp/test/MementoTimeGateTests.java, components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAV.java, components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAVResponseFilter.java, core/http/src/main/java/org/trellisldp/http/CacheControlFilter.java, core/http/src/main/java/org/trellisldp/http/Trellis.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpFilter.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/main/java/org/trellisldp/http/WebSubHeaderFilter.java
=> Bind JAX-RS filters to matched Trellis resources

.github/workflows/cd-config.yml, .github/workflows/ci-config.yml, .travis.yml, README.md, azure-pipelines.yml, build.gradle
This adjusts the CI/CD configuration to use `main` as the default branch.
Resolves #994
=> Use main as default branch

core/http/src/main/java/org/trellisldp/http/impl/HttpUtils.java, core/http/src/test/java/org/trellisldp/http/impl/HttpUtilsTest.java
=> Adjust content negotiation for binaries

auth/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, components/dropwizard/src/main/java/org/trellisldp/dropwizard/CrossOriginResourceSharingFilter.java, components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAV.java, components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAVResponseFilter.java, core/http/src/main/java/org/trellisldp/http/CacheControlFilter.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpFilter.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/main/java/org/trellisldp/http/WebSubHeaderFilter.java, core/http/src/main/java/org/trellisldp/http/core/LdpResource.java
=> Use LdpResource as NameBinding annotation

.github/workflows/ci-config.yml, .travis.yml, build.gradle
=> Use Java11 for Sonar

components/jdbc/build.gradle
The jdbc component is missing a test-scoped logger
=> Add test logger

.github/workflows/cd-config.yml, .github/workflows/ci-config.yml, .travis.yml, auth/jwt/build.gradle, build.gradle, components/app/build.gradle, components/cdi/build.gradle, components/dropwizard/build.gradle, components/jdbc/src/main/java/org/trellisldp/jdbc/DBUtils.java, components/jdbc/src/main/java/org/trellisldp/jdbc/DBWrappedMementoService.java, components/jdbc/src/test/java/org/trellisldp/jdbc/DBUtilsTest.java, components/webdav/build.gradle, core/api/src/main/java/org/trellisldp/api/RDFFactory.java, core/api/src/test/java/org/trellisldp/api/RDFFactoryTest.java, core/http/build.gradle, core/http/src/main/java/module-info.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java, notifications/amqp/build.gradle, notifications/jms/build.gradle, notifications/reactive/build.gradle, platform/bom/build.gradle, platform/dropwizard/build.gradle, platform/openliberty/build.gradle, platform/osgi/build.gradle, platform/osgi/src/test/java/org/trellisldp/osgi/OSGiTest.java, platform/quarkus/build.gradle
=> Use Java 11 source target

components/constraint/src/main/java/org/trellisldp/constraint/LdpConstraintService.java, components/file/src/main/java/org/trellisldp/file/FileResource.java, components/jdbc/src/main/java/org/trellisldp/jdbc/DBResource.java, components/jena/src/main/java/org/trellisldp/jena/JenaIOService.java, components/test/src/main/java/org/trellisldp/test/InMemoryResourceService.java, components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResource.java, components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java, core/api/src/main/java/org/trellisldp/api/TrellisUtils.java, core/common/src/main/java/org/trellisldp/common/HttpConstants.java, core/http/src/main/java/org/trellisldp/http/impl/HttpUtils.java, core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java
Java 11 makes it easier to create immutable collections.
=> Use simpler immutable collection creation

.github/workflows/codeql-analysis.yml
This adds the beta code analysis workflow
=> Add codeQL analysis

auth/basic/build.gradle, auth/basic/src/main/java/org/trellisldp/auth/basic/BasicAuthFilter.java, auth/basic/src/test/java/org/trellisldp/auth/basic/BasicAuthFilterTest.java, auth/jwt/build.gradle, auth/jwt/src/main/java/module-info.java, auth/jwt/src/main/java/org/trellisldp/jwt/WebIdSecurityContext.java, auth/jwt/src/test/java/org/trellisldp/jwt/WebIdSecurityContextTest.java, auth/oauth/build.gradle, auth/oauth/src/main/java/module-info.java, auth/oauth/src/main/java/org/trellisldp/oauth/OAuthFilter.java, auth/oauth/src/test/java/org/trellisldp/oauth/OAuthFilterTest.java, components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAV.java, core/common/src/main/java/org/trellisldp/common/HttpSession.java, core/common/src/main/java/org/trellisldp/common/TrellisRoles.java, core/common/src/test/java/org/trellisldp/common/HttpSessionTest.java, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java
=> Use security annotations

components/dropwizard/src/main/java/org/trellisldp/dropwizard/AbstractTrellisApplication.java
=> Inject ResourceService into Dropwizard runtime

build.gradle, components/webdav/src/test/java/org/trellisldp/webdav/AbstractWebDAVTest.java, core/common/src/test/java/org/trellisldp/common/PreferTest.java, core/common/src/test/java/org/trellisldp/common/SlugTest.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java
This makes it possible to simplify a number of tests.
=> Parameterize tests, where appropriate

components/triplestore/src/test/java/org/trellisldp/triplestore/TriplestoreResourceServiceTest.java
This simplifies and will speed up the triplestore-based tests.
=> Reduce the number of requests for testing

build.gradle, components/test/build.gradle, platform/osgi/build.gradle
This simplifies the JUnit dependency declarations
=> Simplify junit dependencies

auth/basic/build.gradle, auth/jwt/build.gradle, auth/oauth/build.gradle, auth/webac/build.gradle, build.gradle, components/dropwizard/build.gradle, components/file/build.gradle, components/jdbc/build.gradle, components/jena/build.gradle, components/namespace/build.gradle, components/rdfa/build.gradle, components/test/build.gradle, components/triplestore/build.gradle, components/webdav/build.gradle, core/common/build.gradle, core/http/build.gradle, notifications/amqp/build.gradle, notifications/jms/build.gradle, notifications/kafka/build.gradle, platform/openliberty/build.gradle
This simplifies MicroProfile dependency management
=> Use microprofile platform

.github/workflows/cd-config.yml, .github/workflows/ci-config.yml, .github/workflows/codeql-analysis.yml
This updates the GH Action versions.
=> Update GH Action versions

components/jena/src/main/java/org/trellisldp/jena/JenaIOService.java
=> Better support for Unicode paths

components/file/src/main/java/org/trellisldp/file/FileBinaryService.java, components/test/src/main/java/org/trellisldp/test/AbstractApplicationAuthTests.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java, core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java
=> Encode URIs using UriBuilder

components/test/src/main/java/org/trellisldp/test/LdpRdfTests.java
This adds tests for space encoding
=> Add test for spaces

components/jena/src/main/java/org/trellisldp/jena/JenaIOService.java, components/jena/src/test/java/org/trellisldp/jena/JenaIOServiceTest.java, components/test/src/main/java/org/trellisldp/test/TestUtils.java, components/webdav/src/test/java/org/trellisldp/webdav/AbstractWebDAVTest.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/impl/HttpUtilsTest.java
This makes the Jena service more CDI-centric
=> CDI-ize Jena service

notifications/amqp/src/main/java/org/trellisldp/amqp/AmqpEventService.java, notifications/amqp/src/test/java/org/trellisldp/amqp/AmqpEventServiceTest.java, notifications/jms/src/main/java/org/trellisldp/jms/JmsEventService.java, notifications/jms/src/test/java/org/trellisldp/jms/JmsEventServiceTest.java, notifications/kafka/src/main/java/org/trellisldp/kafka/KafkaEventService.java, notifications/kafka/src/test/java/org/trellisldp/kafka/KafkaEventServiceTest.java
CDI-ize the notification components.
=> CDI injection for notification services

auth/jwt/src/main/java/org/trellisldp/jwt/JwtAuthFilter.java, auth/webac/src/main/java/org/trellisldp/webac/WebAcFilter.java, auth/webac/src/main/java/org/trellisldp/webac/WebAcService.java, auth/webac/src/test/java/org/trellisldp/webac/WebAcFilterTest.java, auth/webac/src/test/java/org/trellisldp/webac/WebAcServiceTest.java
This adjusts the injection mechanism for the auth components.
=> CDI-ize auth components

components/webdav/build.gradle, components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAV.java, components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAVRequestFilter.java, components/webdav/src/test/java/org/trellisldp/webdav/AbstractWebDAVTest.java, components/webdav/src/test/java/org/trellisldp/webdav/TrellisWebDAVRequestFilterTest.java, components/webdav/src/test/java/org/trellisldp/webdav/WebDAVNoBaseUrlTest.java, components/webdav/src/test/java/org/trellisldp/webdav/WebDAVTest.java
This adjusts the injection mechanism for the WebDAV component
=> CDI-ize webdav component

components/webdav/build.gradle, components/webdav/src/test/java/org/trellisldp/webdav/WebDAVNoBaseUrlTest.java, components/webdav/src/test/java/org/trellisldp/webdav/WebDAVTest.java, core/http/build.gradle, core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceAdminTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceBaseUrlTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceNoAgentTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceUserTest.java
This makes the injection mechanism more consistent across Trellis
=> Use CDI field injection for http layer

auth/webac/src/test/java/org/trellisldp/webac/WebAcFilterTest.java, auth/webac/src/test/java/org/trellisldp/webac/WebAcServiceTest.java, core/api/src/test/java/org/trellisldp/api/BinaryServiceTest.java, core/api/src/test/java/org/trellisldp/api/NoopMementoServiceTest.java, core/api/src/test/java/org/trellisldp/api/ResourceServiceTest.java, core/common/src/test/java/org/trellisldp/common/HttpSessionTest.java, core/http/src/test/java/org/trellisldp/http/impl/BaseTestHandler.java, core/http/src/test/java/org/trellisldp/http/impl/GetHandlerTest.java, core/http/src/test/java/org/trellisldp/http/impl/PatchHandlerTest.java, notifications/jms/src/test/java/org/trellisldp/jms/JmsEventServiceTest.java
This cleans up some superfluous mockito matchers
=> Mockito cleanup

components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAV.java
This normalizes `@Context` injection in the WebDAV component
=> Use consistent injection with WebDAV component

components/jdbc/src/test/java/org/trellisldp/jdbc/ResourceDataTest.java, core/http/src/test/java/org/trellisldp/http/AbstractTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/BaseTrellisHttpResourceTest.java, core/http/src/test/java/org/trellisldp/http/TrellisHttpResourceTest.java
=> Clean up mockito matchers

components/rdfa/src/main/java/org/trellisldp/rdfa/DefaultRdfaWriterService.java, components/rdfa/src/test/java/org/trellisldp/rdfa/DefaultRdfaWriterServiceTest.java, core/http/src/main/java/org/trellisldp/http/impl/GetHandler.java
This simply removes ETag consideration from HTML representations
=> Do not include/consider ETags on HTML/RDFa responses

core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java
=> Review OpenAPI annotations

build.gradle, components/jdbc/build.gradle, components/jdbc/src/test/java/org/trellisldp/jdbc/DBNamespaceServiceTest.java, components/jdbc/src/test/java/org/trellisldp/jdbc/DBResourceTest.java, components/jdbc/src/test/java/org/trellisldp/jdbc/DBTestUtils.java, components/jdbc/src/test/java/org/trellisldp/jdbc/DBWrappedMementoServiceTest.java, components/jdbc/src/test/java/org/trellisldp/jdbc/ResourceDataTest.java, components/jdbc/src/test/java/org/trellisldp/jdbc/ResourceServiceTest.java
=> Use testcontainers for postgres testing

notifications/jackson/src/main/java/org/trellisldp/notification/jackson/ActivityStreamMessage.java, notifications/jackson/src/test/java/org/trellisldp/notification/jackson/DefaultNotificationSerializationServiceTest.java, notifications/jsonb/src/main/java/org/trellisldp/notification/jsonb/ActivityStreamMessage.java, notifications/jsonb/src/test/java/org/trellisldp/notification/jsonb/DefaultNotificationSerializationServiceTest.java
This simplifies the notification structure
=> Use trellis context in notification message

notifications/jackson/src/main/java/org/trellisldp/notification/jackson/ActivityStreamMessage.java, notifications/jsonb/src/main/java/org/trellisldp/notification/jsonb/ActivityStreamMessage.java, notifications/jsonb/src/test/java/org/trellisldp/notification/jsonb/DefaultNotificationSerializationServiceTest.java
This replaces the trellis property with a more standard one
=> Use httph vocabulary for state param

build.gradle, platform/quarkus/src/main/docker/Dockerfile.jvm
This adjusts the Docker layout for Quarkus version 1.12
=> Update to quarkus 1.12

platform/osgi/src/test/java/org/trellisldp/osgi/OSGiTest.java
=> Remove ActiveMQ references
